// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/tangopb (interfaces: TangoServiceGetChangedTargetsAndEdgesYARPCServer,TangoServiceGetChangedTargetsYARPCServer,TangoServiceGetTargetGraphYARPCServer)
//
// Generated by this command:
//
//	mockgen -package=tangopbmock -self_package=tangopbmock -destination=tangopbmock/tangopbmock.go . TangoServiceGetChangedTargetsAndEdgesYARPCServer,TangoServiceGetChangedTargetsYARPCServer,TangoServiceGetTargetGraphYARPCServer
//

// Package tangopbmock is a generated GoMock package.
package tangopbmock

import (
	context "context"
	reflect "reflect"

	tangopb "github.com/uber/tango/tangopb"
	gomock "go.uber.org/mock/gomock"
	yarpc "go.uber.org/yarpc"
)

// MockTangoServiceGetChangedTargetsAndEdgesYARPCServer is a mock of TangoServiceGetChangedTargetsAndEdgesYARPCServer interface.
type MockTangoServiceGetChangedTargetsAndEdgesYARPCServer struct {
	ctrl     *gomock.Controller
	recorder *MockTangoServiceGetChangedTargetsAndEdgesYARPCServerMockRecorder
	isgomock struct{}
}

// MockTangoServiceGetChangedTargetsAndEdgesYARPCServerMockRecorder is the mock recorder for MockTangoServiceGetChangedTargetsAndEdgesYARPCServer.
type MockTangoServiceGetChangedTargetsAndEdgesYARPCServerMockRecorder struct {
	mock *MockTangoServiceGetChangedTargetsAndEdgesYARPCServer
}

// NewMockTangoServiceGetChangedTargetsAndEdgesYARPCServer creates a new mock instance.
func NewMockTangoServiceGetChangedTargetsAndEdgesYARPCServer(ctrl *gomock.Controller) *MockTangoServiceGetChangedTargetsAndEdgesYARPCServer {
	mock := &MockTangoServiceGetChangedTargetsAndEdgesYARPCServer{ctrl: ctrl}
	mock.recorder = &MockTangoServiceGetChangedTargetsAndEdgesYARPCServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTangoServiceGetChangedTargetsAndEdgesYARPCServer) EXPECT() *MockTangoServiceGetChangedTargetsAndEdgesYARPCServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTangoServiceGetChangedTargetsAndEdgesYARPCServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTangoServiceGetChangedTargetsAndEdgesYARPCServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTangoServiceGetChangedTargetsAndEdgesYARPCServer)(nil).Context))
}

// Send mocks base method.
func (m *MockTangoServiceGetChangedTargetsAndEdgesYARPCServer) Send(arg0 *tangopb.GetChangedTargetsAndEdgesResponse, arg1 ...yarpc.StreamOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTangoServiceGetChangedTargetsAndEdgesYARPCServerMockRecorder) Send(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTangoServiceGetChangedTargetsAndEdgesYARPCServer)(nil).Send), varargs...)
}

// MockTangoServiceGetChangedTargetsYARPCServer is a mock of TangoServiceGetChangedTargetsYARPCServer interface.
type MockTangoServiceGetChangedTargetsYARPCServer struct {
	ctrl     *gomock.Controller
	recorder *MockTangoServiceGetChangedTargetsYARPCServerMockRecorder
	isgomock struct{}
}

// MockTangoServiceGetChangedTargetsYARPCServerMockRecorder is the mock recorder for MockTangoServiceGetChangedTargetsYARPCServer.
type MockTangoServiceGetChangedTargetsYARPCServerMockRecorder struct {
	mock *MockTangoServiceGetChangedTargetsYARPCServer
}

// NewMockTangoServiceGetChangedTargetsYARPCServer creates a new mock instance.
func NewMockTangoServiceGetChangedTargetsYARPCServer(ctrl *gomock.Controller) *MockTangoServiceGetChangedTargetsYARPCServer {
	mock := &MockTangoServiceGetChangedTargetsYARPCServer{ctrl: ctrl}
	mock.recorder = &MockTangoServiceGetChangedTargetsYARPCServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTangoServiceGetChangedTargetsYARPCServer) EXPECT() *MockTangoServiceGetChangedTargetsYARPCServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTangoServiceGetChangedTargetsYARPCServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTangoServiceGetChangedTargetsYARPCServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTangoServiceGetChangedTargetsYARPCServer)(nil).Context))
}

// Send mocks base method.
func (m *MockTangoServiceGetChangedTargetsYARPCServer) Send(arg0 *tangopb.GetChangedTargetsResponse, arg1 ...yarpc.StreamOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTangoServiceGetChangedTargetsYARPCServerMockRecorder) Send(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTangoServiceGetChangedTargetsYARPCServer)(nil).Send), varargs...)
}

// MockTangoServiceGetTargetGraphYARPCServer is a mock of TangoServiceGetTargetGraphYARPCServer interface.
type MockTangoServiceGetTargetGraphYARPCServer struct {
	ctrl     *gomock.Controller
	recorder *MockTangoServiceGetTargetGraphYARPCServerMockRecorder
	isgomock struct{}
}

// MockTangoServiceGetTargetGraphYARPCServerMockRecorder is the mock recorder for MockTangoServiceGetTargetGraphYARPCServer.
type MockTangoServiceGetTargetGraphYARPCServerMockRecorder struct {
	mock *MockTangoServiceGetTargetGraphYARPCServer
}

// NewMockTangoServiceGetTargetGraphYARPCServer creates a new mock instance.
func NewMockTangoServiceGetTargetGraphYARPCServer(ctrl *gomock.Controller) *MockTangoServiceGetTargetGraphYARPCServer {
	mock := &MockTangoServiceGetTargetGraphYARPCServer{ctrl: ctrl}
	mock.recorder = &MockTangoServiceGetTargetGraphYARPCServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTangoServiceGetTargetGraphYARPCServer) EXPECT() *MockTangoServiceGetTargetGraphYARPCServerMockRecorder {
	return m.recorder
}

// Context mocks base method.
func (m *MockTangoServiceGetTargetGraphYARPCServer) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockTangoServiceGetTargetGraphYARPCServerMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockTangoServiceGetTargetGraphYARPCServer)(nil).Context))
}

// Send mocks base method.
func (m *MockTangoServiceGetTargetGraphYARPCServer) Send(arg0 *tangopb.GetTargetGraphResponse, arg1 ...yarpc.StreamOption) error {
	m.ctrl.T.Helper()
	varargs := []any{arg0}
	for _, a := range arg1 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Send", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockTangoServiceGetTargetGraphYARPCServerMockRecorder) Send(arg0 any, arg1 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0}, arg1...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockTangoServiceGetTargetGraphYARPCServer)(nil).Send), varargs...)
}
