# Storage configuration
# Supported types: "memory", "disk"
storage:
  type: "memory"
  # Disk storage configuration (used when type is "disk")
  # disk:
  #   root_path: "/tmp/tango-storage"

# Repository configuration
repository:
  remote: "https://github.com/uber/tango.git"
  default_branch: "main"
  full_hash_repos:
    - ""
  excluded_files:
  # bazel_tools is a special repo, it comes with bazel installation as a local_repository, it contains platform dependent
  # files that are not relevant to the build, we don't need to hash it
  # in workspace mode, it's ok because local_repository() definition is
  # almost static
  # in bzlmod mode, we will recurse into bazel_tools repo and hash those
  # non-existent files, so we need to exclude them
    - "^@@?bazel_tools/"
  exclude_external_targets: true
  bzlmod_enabled: true
  query_timeout: 300
  git_timeout: 300
