// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/core/targethasher (interfaces: SourceHasher)
//
// Generated by this command:
//
//	mockgen -package=targethasher -destination=core/targethasher/mock_sourcehasher_test.go github.com/uber/tango/core/targethasher SourceHasher
//

// Package targethasher is a generated GoMock package.
package targethasher

import (
	reflect "reflect"

	build_proto "github.com/bazelbuild/buildtools/build_proto"
	gomock "go.uber.org/mock/gomock"
)

// MockSourceHasher is a mock of SourceHasher interface.
type MockSourceHasher struct {
	ctrl     *gomock.Controller
	recorder *MockSourceHasherMockRecorder
	isgomock struct{}
}

// MockSourceHasherMockRecorder is the mock recorder for MockSourceHasher.
type MockSourceHasherMockRecorder struct {
	mock *MockSourceHasher
}

// NewMockSourceHasher creates a new mock instance.
func NewMockSourceHasher(ctrl *gomock.Controller) *MockSourceHasher {
	mock := &MockSourceHasher{ctrl: ctrl}
	mock.recorder = &MockSourceHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceHasher) EXPECT() *MockSourceHasherMockRecorder {
	return m.recorder
}

// HashSourceFile mocks base method.
func (m *MockSourceHasher) HashSourceFile(s *build_proto.SourceFile) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashSourceFile", s)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashSourceFile indicates an expected call of HashSourceFile.
func (mr *MockSourceHasherMockRecorder) HashSourceFile(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashSourceFile", reflect.TypeOf((*MockSourceHasher)(nil).HashSourceFile), s)
}
