// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/core/targethasher (interfaces: SourceHasher)

// Package targethasher is a generated GoMock package.
package targethasher

import (
	context "context"
	reflect "reflect"

	build_proto "github.com/bazelbuild/buildtools/build_proto"
	gomock "github.com/golang/mock/gomock"
)

// MockSourceHasher is a mock of SourceHasher interface.
type MockSourceHasher struct {
	ctrl     *gomock.Controller
	recorder *MockSourceHasherMockRecorder
}

// MockSourceHasherMockRecorder is the mock recorder for MockSourceHasher.
type MockSourceHasherMockRecorder struct {
	mock *MockSourceHasher
}

// NewMockSourceHasher creates a new mock instance.
func NewMockSourceHasher(ctrl *gomock.Controller) *MockSourceHasher {
	mock := &MockSourceHasher{ctrl: ctrl}
	mock.recorder = &MockSourceHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceHasher) EXPECT() *MockSourceHasherMockRecorder {
	return m.recorder
}

// HashSourceFile mocks base method.
func (m *MockSourceHasher) HashSourceFile(arg0 context.Context, arg1 *build_proto.SourceFile) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HashSourceFile", arg0, arg1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HashSourceFile indicates an expected call of HashSourceFile.
func (mr *MockSourceHasherMockRecorder) HashSourceFile(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HashSourceFile", reflect.TypeOf((*MockSourceHasher)(nil).HashSourceFile), arg0, arg1)
}
