// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/core/bazel (interfaces: Bazel)
//
// Generated by this command:
//
//	mockgen -destination=core/bazel/bazelmock/bazelmock.go github.com/uber/tango/core/bazel Bazel
//

// Package bazelmock is a generated GoMock package.
package bazelmock

import (
	context "context"
	reflect "reflect"

	bazel "github.com/uber/tango/core/bazel"
	gomock "go.uber.org/mock/gomock"
)

// MockBazel is a mock of Bazel interface.
type MockBazel struct {
	ctrl     *gomock.Controller
	recorder *MockBazelMockRecorder
	isgomock struct{}
}

// MockBazelMockRecorder is the mock recorder for MockBazel.
type MockBazelMockRecorder struct {
	mock *MockBazel
}

// NewMockBazel creates a new mock instance.
func NewMockBazel(ctrl *gomock.Controller) *MockBazel {
	mock := &MockBazel{ctrl: ctrl}
	mock.recorder = &MockBazelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBazel) EXPECT() *MockBazelMockRecorder {
	return m.recorder
}

// ExecuteQuery mocks base method.
func (m *MockBazel) ExecuteQuery(ctx context.Context, req *bazel.QueryRequest) (*bazel.QueryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExecuteQuery", ctx, req)
	ret0, _ := ret[0].(*bazel.QueryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExecuteQuery indicates an expected call of ExecuteQuery.
func (mr *MockBazelMockRecorder) ExecuteQuery(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExecuteQuery", reflect.TypeOf((*MockBazel)(nil).ExecuteQuery), ctx, req)
}
