load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "entity",
    srcs = [
        "build_description.go",
        "change_type.go",
        "changed_targets.go",
        "computation_strategy.go",
        "optimized_target.go",
        "target_graph.go",
    ],
    importpath = "github.com/uber/tango/entity",
    visibility = ["//visibility:public"],
    deps = ["//internal/streaming/wire"],
)

go_test(
    name = "entity_test",
    srcs = ["optimized_target_test.go"],
    embed = [":entity"],
    deps = ["@com_github_stretchr_testify//assert"],
)
