// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/core/repomanager (interfaces: RepoManager)
//
// Generated by this command:
//
//	mockgen -destination=core/repomanager/mock/repomanagermock.go github.com/uber/tango/core/repomanager RepoManager
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	workspace "github.com/uber/tango/core/workspace"
	entity "github.com/uber/tango/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRepoManager is a mock of RepoManager interface.
type MockRepoManager struct {
	ctrl     *gomock.Controller
	recorder *MockRepoManagerMockRecorder
	isgomock struct{}
}

// MockRepoManagerMockRecorder is the mock recorder for MockRepoManager.
type MockRepoManagerMockRecorder struct {
	mock *MockRepoManager
}

// NewMockRepoManager creates a new mock instance.
func NewMockRepoManager(ctrl *gomock.Controller) *MockRepoManager {
	mock := &MockRepoManager{ctrl: ctrl}
	mock.recorder = &MockRepoManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepoManager) EXPECT() *MockRepoManagerMockRecorder {
	return m.recorder
}

// Lease mocks base method.
func (m *MockRepoManager) Lease(ctx context.Context, desc entity.BuildDescription) (workspace.Workspace, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lease", ctx, desc)
	ret0, _ := ret[0].(workspace.Workspace)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lease indicates an expected call of Lease.
func (mr *MockRepoManagerMockRecorder) Lease(ctx, desc any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lease", reflect.TypeOf((*MockRepoManager)(nil).Lease), ctx, desc)
}
