// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: tango.proto

package tangopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// TangoYARPCClient is the YARPC client-side interface for the Tango service.
type TangoYARPCClient interface {
	GetTargetGraph(context.Context, *GetTargetGraphRequest, ...yarpc.CallOption) (TangoServiceGetTargetGraphYARPCClient, error)
	GetChangedTargets(context.Context, *GetChangedTargetsRequest, ...yarpc.CallOption) (TangoServiceGetChangedTargetsYARPCClient, error)
	GetChangedServices(context.Context, *GetChangedServicesRequest, ...yarpc.CallOption) (TangoServiceGetChangedServicesYARPCClient, error)
	GetChangedTargetGraph(context.Context, *GetChangedTargetGraphRequest, ...yarpc.CallOption) (TangoServiceGetChangedTargetGraphYARPCClient, error)
}

// TangoServiceGetTargetGraphYARPCClient receives GetTargetGraphResponses, returning io.EOF when the stream is complete.
type TangoServiceGetTargetGraphYARPCClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetTargetGraphResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// TangoServiceGetChangedTargetsYARPCClient receives GetChangedTargetsResponses, returning io.EOF when the stream is complete.
type TangoServiceGetChangedTargetsYARPCClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetChangedTargetsResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// TangoServiceGetChangedServicesYARPCClient receives GetChangedServicesResponses, returning io.EOF when the stream is complete.
type TangoServiceGetChangedServicesYARPCClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetChangedServicesResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// TangoServiceGetChangedTargetGraphYARPCClient receives GetChangedTargetGraphResponses, returning io.EOF when the stream is complete.
type TangoServiceGetChangedTargetGraphYARPCClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetChangedTargetGraphResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

func newTangoYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) TangoYARPCClient {
	return &_TangoYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.tango.Tango",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewTangoYARPCClient builds a new YARPC client for the Tango service.
func NewTangoYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) TangoYARPCClient {
	return newTangoYARPCClient(clientConfig, nil, options...)
}

// TangoYARPCServer is the YARPC server-side interface for the Tango service.
type TangoYARPCServer interface {
	GetTargetGraph(*GetTargetGraphRequest, TangoServiceGetTargetGraphYARPCServer) error
	GetChangedTargets(*GetChangedTargetsRequest, TangoServiceGetChangedTargetsYARPCServer) error
	GetChangedServices(*GetChangedServicesRequest, TangoServiceGetChangedServicesYARPCServer) error
	GetChangedTargetGraph(*GetChangedTargetGraphRequest, TangoServiceGetChangedTargetGraphYARPCServer) error
}

// TangoServiceGetTargetGraphYARPCServer sends GetTargetGraphResponses.
type TangoServiceGetTargetGraphYARPCServer interface {
	Context() context.Context
	Send(*GetTargetGraphResponse, ...yarpc.StreamOption) error
}

// TangoServiceGetChangedTargetsYARPCServer sends GetChangedTargetsResponses.
type TangoServiceGetChangedTargetsYARPCServer interface {
	Context() context.Context
	Send(*GetChangedTargetsResponse, ...yarpc.StreamOption) error
}

// TangoServiceGetChangedServicesYARPCServer sends GetChangedServicesResponses.
type TangoServiceGetChangedServicesYARPCServer interface {
	Context() context.Context
	Send(*GetChangedServicesResponse, ...yarpc.StreamOption) error
}

// TangoServiceGetChangedTargetGraphYARPCServer sends GetChangedTargetGraphResponses.
type TangoServiceGetChangedTargetGraphYARPCServer interface {
	Context() context.Context
	Send(*GetChangedTargetGraphResponse, ...yarpc.StreamOption) error
}

type buildTangoYARPCProceduresParams struct {
	Server      TangoYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildTangoYARPCProcedures(params buildTangoYARPCProceduresParams) []transport.Procedure {
	handler := &_TangoYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName:         "uber.tango.Tango",
			UnaryHandlerParams:  []protobuf.BuildProceduresUnaryHandlerParams{},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{

				{
					MethodName: "GetTargetGraph",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.GetTargetGraph,
						},
					),
				},
				{
					MethodName: "GetChangedTargets",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.GetChangedTargets,
						},
					),
				},
				{
					MethodName: "GetChangedServices",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.GetChangedServices,
						},
					),
				},
				{
					MethodName: "GetChangedTargetGraph",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.GetChangedTargetGraph,
						},
					),
				},
			},
		},
	)
}

// BuildTangoYARPCProcedures prepares an implementation of the Tango service for YARPC registration.
func BuildTangoYARPCProcedures(server TangoYARPCServer) []transport.Procedure {
	return buildTangoYARPCProcedures(buildTangoYARPCProceduresParams{Server: server})
}

// FxTangoYARPCClientParams defines the input
// for NewFxTangoYARPCClient. It provides the
// paramaters to get a TangoYARPCClient in an
// Fx application.
type FxTangoYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxTangoYARPCClientResult defines the output
// of NewFxTangoYARPCClient. It provides a
// TangoYARPCClient to an Fx application.
type FxTangoYARPCClientResult struct {
	fx.Out

	Client TangoYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxTangoYARPCClient provides a TangoYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  tangopb.NewFxTangoYARPCClient("service-name"),
//	  ...
//	)
func NewFxTangoYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxTangoYARPCClientParams) FxTangoYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxTangoYARPCClientResult{
			Client: newTangoYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxTangoYARPCProceduresParams defines the input
// for NewFxTangoYARPCProcedures. It provides the
// paramaters to get TangoYARPCServer procedures in an
// Fx application.
type FxTangoYARPCProceduresParams struct {
	fx.In

	Server      TangoYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxTangoYARPCProceduresResult defines the output
// of NewFxTangoYARPCProcedures. It provides
// TangoYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxTangoYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxTangoYARPCProcedures provides TangoYARPCServer procedures to an Fx application.
// It expects a TangoYARPCServer to be present in the container.
//
//	fx.Provide(
//	  tangopb.NewFxTangoYARPCProcedures(),
//	  ...
//	)
func NewFxTangoYARPCProcedures() interface{} {
	return func(params FxTangoYARPCProceduresParams) FxTangoYARPCProceduresResult {
		return FxTangoYARPCProceduresResult{
			Procedures: buildTangoYARPCProcedures(buildTangoYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: TangoReflectionMeta,
		}
	}
}

// TangoReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var TangoReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.tango.Tango",
	FileDescriptors: yarpcFileDescriptorClosurec4210c857dbeec96,
}

type _TangoYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_TangoYARPCCaller) GetTargetGraph(ctx context.Context, request *GetTargetGraphRequest, options ...yarpc.CallOption) (TangoServiceGetTargetGraphYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "GetTargetGraph", options...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(request); err != nil {
		return nil, err
	}
	return &_TangoServiceGetTargetGraphYARPCClient{stream: stream}, nil
}

func (c *_TangoYARPCCaller) GetChangedTargets(ctx context.Context, request *GetChangedTargetsRequest, options ...yarpc.CallOption) (TangoServiceGetChangedTargetsYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "GetChangedTargets", options...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(request); err != nil {
		return nil, err
	}
	return &_TangoServiceGetChangedTargetsYARPCClient{stream: stream}, nil
}

func (c *_TangoYARPCCaller) GetChangedServices(ctx context.Context, request *GetChangedServicesRequest, options ...yarpc.CallOption) (TangoServiceGetChangedServicesYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "GetChangedServices", options...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(request); err != nil {
		return nil, err
	}
	return &_TangoServiceGetChangedServicesYARPCClient{stream: stream}, nil
}

func (c *_TangoYARPCCaller) GetChangedTargetGraph(ctx context.Context, request *GetChangedTargetGraphRequest, options ...yarpc.CallOption) (TangoServiceGetChangedTargetGraphYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "GetChangedTargetGraph", options...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(request); err != nil {
		return nil, err
	}
	return &_TangoServiceGetChangedTargetGraphYARPCClient{stream: stream}, nil
}

type _TangoYARPCHandler struct {
	server TangoYARPCServer
}

func (h *_TangoYARPCHandler) GetTargetGraph(serverStream *protobuf.ServerStream) error {
	requestMessage, err := serverStream.Receive(newTangoServiceGetTargetGraphYARPCRequest)
	if requestMessage == nil {
		return err
	}

	request, ok := requestMessage.(*GetTargetGraphRequest)
	if !ok {
		return protobuf.CastError(emptyTangoServiceGetTargetGraphYARPCRequest, requestMessage)
	}
	return h.server.GetTargetGraph(request, &_TangoServiceGetTargetGraphYARPCServer{serverStream: serverStream})
}

func (h *_TangoYARPCHandler) GetChangedTargets(serverStream *protobuf.ServerStream) error {
	requestMessage, err := serverStream.Receive(newTangoServiceGetChangedTargetsYARPCRequest)
	if requestMessage == nil {
		return err
	}

	request, ok := requestMessage.(*GetChangedTargetsRequest)
	if !ok {
		return protobuf.CastError(emptyTangoServiceGetChangedTargetsYARPCRequest, requestMessage)
	}
	return h.server.GetChangedTargets(request, &_TangoServiceGetChangedTargetsYARPCServer{serverStream: serverStream})
}

func (h *_TangoYARPCHandler) GetChangedServices(serverStream *protobuf.ServerStream) error {
	requestMessage, err := serverStream.Receive(newTangoServiceGetChangedServicesYARPCRequest)
	if requestMessage == nil {
		return err
	}

	request, ok := requestMessage.(*GetChangedServicesRequest)
	if !ok {
		return protobuf.CastError(emptyTangoServiceGetChangedServicesYARPCRequest, requestMessage)
	}
	return h.server.GetChangedServices(request, &_TangoServiceGetChangedServicesYARPCServer{serverStream: serverStream})
}

func (h *_TangoYARPCHandler) GetChangedTargetGraph(serverStream *protobuf.ServerStream) error {
	requestMessage, err := serverStream.Receive(newTangoServiceGetChangedTargetGraphYARPCRequest)
	if requestMessage == nil {
		return err
	}

	request, ok := requestMessage.(*GetChangedTargetGraphRequest)
	if !ok {
		return protobuf.CastError(emptyTangoServiceGetChangedTargetGraphYARPCRequest, requestMessage)
	}
	return h.server.GetChangedTargetGraph(request, &_TangoServiceGetChangedTargetGraphYARPCServer{serverStream: serverStream})
}

type _TangoServiceGetTargetGraphYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_TangoServiceGetTargetGraphYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_TangoServiceGetTargetGraphYARPCClient) Recv(options ...yarpc.StreamOption) (*GetTargetGraphResponse, error) {
	responseMessage, err := c.stream.Receive(newTangoServiceGetTargetGraphYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetTargetGraphResponse)
	if !ok {
		return nil, protobuf.CastError(emptyTangoServiceGetTargetGraphYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_TangoServiceGetTargetGraphYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _TangoServiceGetChangedTargetsYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_TangoServiceGetChangedTargetsYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_TangoServiceGetChangedTargetsYARPCClient) Recv(options ...yarpc.StreamOption) (*GetChangedTargetsResponse, error) {
	responseMessage, err := c.stream.Receive(newTangoServiceGetChangedTargetsYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetChangedTargetsResponse)
	if !ok {
		return nil, protobuf.CastError(emptyTangoServiceGetChangedTargetsYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_TangoServiceGetChangedTargetsYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _TangoServiceGetChangedServicesYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_TangoServiceGetChangedServicesYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_TangoServiceGetChangedServicesYARPCClient) Recv(options ...yarpc.StreamOption) (*GetChangedServicesResponse, error) {
	responseMessage, err := c.stream.Receive(newTangoServiceGetChangedServicesYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetChangedServicesResponse)
	if !ok {
		return nil, protobuf.CastError(emptyTangoServiceGetChangedServicesYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_TangoServiceGetChangedServicesYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _TangoServiceGetChangedTargetGraphYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_TangoServiceGetChangedTargetGraphYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_TangoServiceGetChangedTargetGraphYARPCClient) Recv(options ...yarpc.StreamOption) (*GetChangedTargetGraphResponse, error) {
	responseMessage, err := c.stream.Receive(newTangoServiceGetChangedTargetGraphYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetChangedTargetGraphResponse)
	if !ok {
		return nil, protobuf.CastError(emptyTangoServiceGetChangedTargetGraphYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_TangoServiceGetChangedTargetGraphYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _TangoServiceGetTargetGraphYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_TangoServiceGetTargetGraphYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_TangoServiceGetTargetGraphYARPCServer) Send(response *GetTargetGraphResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

type _TangoServiceGetChangedTargetsYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_TangoServiceGetChangedTargetsYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_TangoServiceGetChangedTargetsYARPCServer) Send(response *GetChangedTargetsResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

type _TangoServiceGetChangedServicesYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_TangoServiceGetChangedServicesYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_TangoServiceGetChangedServicesYARPCServer) Send(response *GetChangedServicesResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

type _TangoServiceGetChangedTargetGraphYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_TangoServiceGetChangedTargetGraphYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_TangoServiceGetChangedTargetGraphYARPCServer) Send(response *GetChangedTargetGraphResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

func newTangoServiceGetTargetGraphYARPCRequest() proto.Message {
	return &GetTargetGraphRequest{}
}

func newTangoServiceGetTargetGraphYARPCResponse() proto.Message {
	return &GetTargetGraphResponse{}
}

func newTangoServiceGetChangedTargetsYARPCRequest() proto.Message {
	return &GetChangedTargetsRequest{}
}

func newTangoServiceGetChangedTargetsYARPCResponse() proto.Message {
	return &GetChangedTargetsResponse{}
}

func newTangoServiceGetChangedServicesYARPCRequest() proto.Message {
	return &GetChangedServicesRequest{}
}

func newTangoServiceGetChangedServicesYARPCResponse() proto.Message {
	return &GetChangedServicesResponse{}
}

func newTangoServiceGetChangedTargetGraphYARPCRequest() proto.Message {
	return &GetChangedTargetGraphRequest{}
}

func newTangoServiceGetChangedTargetGraphYARPCResponse() proto.Message {
	return &GetChangedTargetGraphResponse{}
}

var (
	emptyTangoServiceGetTargetGraphYARPCRequest         = &GetTargetGraphRequest{}
	emptyTangoServiceGetTargetGraphYARPCResponse        = &GetTargetGraphResponse{}
	emptyTangoServiceGetChangedTargetsYARPCRequest      = &GetChangedTargetsRequest{}
	emptyTangoServiceGetChangedTargetsYARPCResponse     = &GetChangedTargetsResponse{}
	emptyTangoServiceGetChangedServicesYARPCRequest     = &GetChangedServicesRequest{}
	emptyTangoServiceGetChangedServicesYARPCResponse    = &GetChangedServicesResponse{}
	emptyTangoServiceGetChangedTargetGraphYARPCRequest  = &GetChangedTargetGraphRequest{}
	emptyTangoServiceGetChangedTargetGraphYARPCResponse = &GetChangedTargetGraphResponse{}
)

var yarpcFileDescriptorClosurec4210c857dbeec96 = [][]byte{
	// tango.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0xcb, 0x6e, 0xdb, 0x46,
		0x17, 0x36, 0x75, 0xb1, 0xe9, 0x23, 0x5b, 0xa2, 0xc7, 0xfe, 0x1d, 0x59, 0xce, 0xc5, 0x21, 0x92,
		0xbf, 0x4e, 0x82, 0x2a, 0x85, 0x83, 0xa0, 0x41, 0x8a, 0x2c, 0x6c, 0x99, 0xb1, 0x85, 0x26, 0xb2,
		0x41, 0xd1, 0x29, 0xd2, 0x2e, 0x88, 0x11, 0x39, 0x91, 0x89, 0x8a, 0x97, 0x92, 0xa3, 0xc4, 0xce,
		0x1b, 0x74, 0xd3, 0x75, 0xd1, 0x45, 0x81, 0x16, 0xe8, 0x13, 0xf4, 0x09, 0xfa, 0x0c, 0xdd, 0x76,
		0xdb, 0x02, 0x7d, 0x8b, 0x62, 0x86, 0x23, 0x8a, 0x94, 0xe8, 0x1b, 0xba, 0x29, 0xb2, 0xe3, 0x9c,
		0xcb, 0x77, 0xce, 0xf9, 0xce, 0x99, 0x8b, 0x04, 0x15, 0x8a, 0xbd, 0xbe, 0xdf, 0x0c, 0x42, 0x9f,
		0xfa, 0x08, 0x86, 0x3d, 0x12, 0x36, 0xb9, 0x44, 0x7d, 0x04, 0x73, 0x3a, 0xf9, 0x66, 0x48, 0x22,
		0x8a, 0x14, 0x28, 0x0e, 0xc3, 0x41, 0x5d, 0xda, 0x90, 0x36, 0xe7, 0x75, 0xf6, 0x89, 0x56, 0x61,
		0xd6, 0xf2, 0x5d, 0xd7, 0xa1, 0xf5, 0x02, 0x17, 0x8a, 0x95, 0xfa, 0xab, 0x04, 0xca, 0xce, 0xd0,
		0x19, 0xd8, 0xbb, 0x24, 0xb2, 0x42, 0x27, 0xa0, 0x8e, 0xef, 0x31, 0xe3, 0x90, 0xb8, 0x3e, 0x25,
		0x02, 0x41, 0xac, 0xd0, 0x1a, 0xc8, 0x3d, 0x1c, 0x11, 0x33, 0x3a, 0xc6, 0x02, 0x66, 0x8e, 0xad,
		0xbb, 0xc7, 0x18, 0x3d, 0x04, 0x39, 0x8c, 0x83, 0x47, 0xf5, 0xe2, 0x46, 0x71, 0xb3, 0xb2, 0xb5,
		0xdc, 0x1c, 0xe7, 0xd6, 0x14, 0x89, 0xe9, 0x89, 0x11, 0xfa, 0x0c, 0xe4, 0x88, 0x86, 0x98, 0x92,
		0xfe, 0x69, 0xbd, 0xb4, 0x21, 0x6d, 0x56, 0xb7, 0x6e, 0xa5, 0x1d, 0x5a, 0xbe, 0x1b, 0x0c, 0x29,
		0x66, 0xe9, 0x74, 0x85, 0x99, 0x9e, 0x38, 0xa8, 0x8f, 0xa0, 0xba, 0xeb, 0x44, 0x14, 0x7b, 0x16,
		0x79, 0xee, 0x0c, 0x28, 0x09, 0xd1, 0x6d, 0x58, 0x70, 0xf1, 0x89, 0x69, 0x0b, 0x29, 0x4f, 0xbc,
		0xac, 0x57, 0x5c, 0x7c, 0x32, 0x32, 0x54, 0x7f, 0x28, 0xc0, 0xc2, 0xc1, 0x90, 0x06, 0x43, 0xda,
		0xf2, 0xbd, 0x37, 0x4e, 0x9f, 0xf9, 0x38, 0x9e, 0x35, 0x18, 0xda, 0xc4, 0xa4, 0xb8, 0x1f, 0x71,
		0x1f, 0x59, 0xaf, 0x08, 0x99, 0x81, 0xfb, 0x11, 0xfa, 0x18, 0xd0, 0xc8, 0x04, 0x53, 0x1a, 0x3a,
		0xbd, 0x21, 0x25, 0x11, 0xaf, 0x5d, 0xd6, 0x97, 0x84, 0x66, 0x3b, 0x51, 0xa0, 0xbb, 0x50, 0x1d,
		0x99, 0x1f, 0xe3, 0xe8, 0x98, 0x30, 0x2e, 0x98, 0xe9, 0xa2, 0x90, 0xee, 0x73, 0x21, 0xba, 0x01,
		0x10, 0xfa, 0x3e, 0x8d, 0x4c, 0xdf, 0x1b, 0xc4, 0xd5, 0xcb, 0xfa, 0x3c, 0x97, 0x1c, 0x78, 0x83,
		0x53, 0xf4, 0x00, 0x96, 0x2c, 0x5e, 0x3e, 0x49, 0xea, 0x89, 0xea, 0x65, 0x6e, 0xa5, 0x08, 0xc5,
		0xa8, 0xa8, 0x08, 0x69, 0xa0, 0x50, 0x1c, 0xf6, 0x09, 0x4d, 0xd9, 0xce, 0x6e, 0x48, 0x9b, 0x95,
		0xad, 0x46, 0x9a, 0xcf, 0x2c, 0x5d, 0x7a, 0x2d, 0xf6, 0x49, 0x60, 0xd4, 0xdf, 0x0b, 0x50, 0x3b,
		0x08, 0xa8, 0xe3, 0x3a, 0xef, 0x89, 0x6d, 0x70, 0x25, 0xaa, 0x42, 0xc1, 0xb1, 0x05, 0x93, 0x05,
		0xc7, 0x46, 0x08, 0x4a, 0xac, 0x2a, 0xd1, 0x7a, 0xfe, 0x8d, 0x1e, 0xc2, 0xb2, 0xed, 0x84, 0xc4,
		0xa2, 0xa6, 0x4d, 0x02, 0xe2, 0xd9, 0xc4, 0xb3, 0x1c, 0x12, 0x8f, 0x40, 0x59, 0x47, 0xb1, 0x6a,
		0x37, 0xa5, 0x61, 0x20, 0x9c, 0xec, 0x12, 0xb7, 0xe0, 0xdf, 0x68, 0x1d, 0xe6, 0xc3, 0xe1, 0x80,
		0x98, 0xf4, 0x34, 0x20, 0xbc, 0xd0, 0xb2, 0x2e, 0x33, 0x81, 0x71, 0x1a, 0x10, 0xe6, 0xc0, 0xa8,
		0xe1, 0x45, 0xc9, 0x3a, 0xff, 0x46, 0x0d, 0x90, 0xc9, 0x09, 0x25, 0xa1, 0x87, 0x07, 0xf5, 0x39,
		0x2e, 0x4f, 0xd6, 0xe8, 0x73, 0x80, 0x54, 0xab, 0x64, 0x3e, 0x8b, 0x0f, 0xd2, 0x54, 0x4c, 0x94,
		0xd9, 0x1c, 0xf7, 0x4f, 0xf3, 0x68, 0x78, 0xaa, 0xa7, 0xdc, 0x1b, 0xcf, 0xa0, 0x36, 0xa1, 0x66,
		0x7b, 0xeb, 0x6b, 0x72, 0x2a, 0x68, 0x61, 0x9f, 0x68, 0x05, 0xca, 0x6f, 0xf1, 0x60, 0x48, 0x38,
		0x31, 0x65, 0x3d, 0x5e, 0x3c, 0x2d, 0x3c, 0x91, 0xd4, 0x36, 0x28, 0x13, 0xd1, 0x22, 0xf4, 0x18,
		0xe6, 0x62, 0xf2, 0xd9, 0xc0, 0xb1, 0xe4, 0xd6, 0xcf, 0x49, 0x4e, 0x1f, 0xd9, 0xaa, 0x06, 0x54,
		0x5b, 0xc7, 0xd8, 0xeb, 0x8f, 0x81, 0x76, 0xa0, 0x66, 0xc5, 0x12, 0x33, 0x0b, 0xb8, 0x96, 0xd9,
		0x48, 0x69, 0x27, 0xbd, 0x6a, 0x65, 0x30, 0xd4, 0x3f, 0x24, 0x58, 0xcc, 0x58, 0xa0, 0x4f, 0xa1,
		0x12, 0xdb, 0xc4, 0xdd, 0x90, 0xf8, 0xd6, 0x5c, 0x9d, 0x46, 0x64, 0xbd, 0xd1, 0xc1, 0x4a, 0xbe,
		0xd1, 0x53, 0x00, 0x7f, 0x30, 0x4a, 0x85, 0x53, 0x71, 0x41, 0x69, 0xf3, 0xfe, 0x60, 0x14, 0xf4,
		0x29, 0x80, 0x47, 0xde, 0x8d, 0x7c, 0x8b, 0x97, 0xf0, 0xf5, 0xc8, 0x3b, 0xe1, 0xdb, 0x00, 0x39,
		0xd9, 0xf5, 0xa5, 0x78, 0x76, 0x46, 0x6b, 0xf5, 0xb7, 0x59, 0x90, 0x5f, 0x12, 0x8a, 0x6d, 0x4c,
		0x31, 0x3a, 0x82, 0x25, 0xb1, 0x53, 0x1c, 0xdb, 0x74, 0x71, 0x10, 0x38, 0x5e, 0x5f, 0x30, 0x76,
		0x2f, 0x1d, 0x6b, 0xe4, 0xd0, 0x8c, 0x03, 0xb4, 0xed, 0x97, 0xb1, 0x6d, 0x3c, 0x1d, 0x62, 0xe7,
		0x24, 0x52, 0x06, 0x9b, 0x0c, 0x6f, 0x02, 0x5b, 0x38, 0x07, 0x56, 0x17, 0x93, 0x9d, 0x85, 0x0d,
		0xb3, 0x52, 0xa4, 0xb1, 0x83, 0xbe, 0x9f, 0x00, 0xc6, 0x67, 0xea, 0x9d, 0x33, 0xf2, 0xec, 0x67,
		0xb0, 0x80, 0x26, 0x02, 0x64, 0xc3, 0x6a, 0x32, 0xce, 0xa6, 0x87, 0xdd, 0x71, 0x8a, 0x25, 0x8e,
		0xd8, 0xcc, 0x45, 0x4c, 0x66, 0xbe, 0x83, 0xdd, 0x6c, 0x9e, 0x2b, 0x38, 0x47, 0x85, 0xde, 0xc3,
		0xcd, 0x71, 0x94, 0x88, 0x86, 0x8e, 0xd7, 0x37, 0xf9, 0x2e, 0x48, 0xa2, 0x95, 0x79, 0xb4, 0xc7,
		0xe7, 0x47, 0xeb, 0x72, 0xcf, 0x57, 0xcc, 0x31, 0x13, 0x74, 0x1d, 0x9f, 0x6d, 0xd1, 0xd8, 0x81,
		0x95, 0xbc, 0x46, 0x5d, 0xb4, 0x4f, 0xe7, 0x53, 0xfb, 0x94, 0x61, 0xe4, 0x75, 0xe5, 0x4a, 0x18,
		0xcf, 0xa0, 0x36, 0xd1, 0x88, 0x2b, 0xb9, 0xef, 0xc1, 0xda, 0x99, 0xac, 0x5f, 0x09, 0xa8, 0x03,
		0x1b, 0x17, 0x11, 0x7a, 0x15, 0x3c, 0xf5, 0x27, 0x09, 0xfe, 0xb7, 0x47, 0x68, 0xcc, 0xf1, 0x5e,
		0x88, 0x83, 0xe3, 0xd1, 0x2b, 0xa3, 0x0d, 0x4b, 0x3d, 0xf6, 0x74, 0x30, 0xed, 0xf1, 0xdb, 0x81,
		0x63, 0x56, 0xb6, 0xae, 0xa7, 0x1b, 0x3d, 0xf9, 0xbe, 0xd0, 0x95, 0xde, 0xe4, 0x8b, 0xe3, 0x19,
		0x2c, 0xfa, 0xfc, 0x6a, 0x36, 0x2d, 0x7e, 0x37, 0x8b, 0xf3, 0xa3, 0x9e, 0x39, 0x03, 0x52, 0x77,
		0xb7, 0xbe, 0xe0, 0xa7, 0x56, 0xea, 0x77, 0x12, 0xac, 0x4e, 0xe6, 0x18, 0x05, 0xbe, 0x17, 0x11,
		0xf4, 0x24, 0x7d, 0xdc, 0x4e, 0xa5, 0x36, 0x79, 0x3a, 0xef, 0xcf, 0x24, 0x27, 0x2e, 0xda, 0x02,
		0xd9, 0x15, 0x23, 0x2a, 0xd2, 0x59, 0xc9, 0x1b, 0xdf, 0xfd, 0x19, 0x3d, 0xb1, 0xdb, 0x99, 0x85,
		0x92, 0x43, 0x89, 0xab, 0xfe, 0x29, 0x41, 0x7d, 0x8f, 0xd0, 0xec, 0x89, 0x3d, 0xe2, 0xad, 0x05,
		0xd5, 0x37, 0x4e, 0x18, 0x51, 0x33, 0x24, 0x6f, 0x9d, 0xe8, 0xb2, 0xa4, 0x2d, 0x72, 0x1f, 0x5d,
		0xb8, 0x20, 0x0d, 0x6a, 0x11, 0xb1, 0x7c, 0xcf, 0x1e, 0xa3, 0x14, 0x2e, 0x81, 0x52, 0x8d, 0x9d,
		0x12, 0x98, 0x29, 0xe2, 0x8b, 0x57, 0x22, 0xfe, 0x47, 0x09, 0xd6, 0x72, 0xea, 0x14, 0xdc, 0x6b,
		0x79, 0x37, 0xd4, 0xd4, 0xd3, 0x24, 0xeb, 0xbc, 0x3f, 0x33, 0x79, 0x49, 0xfd, 0xab, 0x46, 0xfc,
		0x95, 0x49, 0xb0, 0x4b, 0xc2, 0xb7, 0x8e, 0x45, 0x3e, 0xc4, 0x4e, 0xf4, 0xa0, 0x91, 0x57, 0xa7,
		0xe8, 0xc4, 0x6d, 0x58, 0x88, 0x62, 0x19, 0xbf, 0x04, 0xc4, 0xbb, 0xbe, 0x22, 0x64, 0xec, 0xbc,
		0x61, 0x26, 0xe2, 0x7a, 0x64, 0x16, 0x11, 0xbf, 0xc2, 0xe6, 0xf5, 0x4a, 0x2c, 0x63, 0x16, 0x91,
		0xfa, 0xb7, 0x04, 0xd7, 0x27, 0xbb, 0x9d, 0x39, 0x11, 0x3e, 0x20, 0x3e, 0x7f, 0x96, 0xe0, 0xc6,
		0x19, 0xb5, 0xfe, 0x67, 0xa6, 0xfb, 0xfe, 0xf7, 0x12, 0x2c, 0xe7, 0xfc, 0x52, 0x42, 0x1b, 0x70,
		0xbd, 0x75, 0xf0, 0xf2, 0xf0, 0xc8, 0xd8, 0x36, 0xda, 0x07, 0x1d, 0xb3, 0x6b, 0xe8, 0xdb, 0x86,
		0xb6, 0xf7, 0xda, 0x6c, 0x77, 0x5e, 0x6d, 0xbf, 0x68, 0xef, 0x2a, 0x33, 0xe8, 0x26, 0x34, 0x72,
		0x2d, 0x8e, 0x3a, 0x5d, 0xcd, 0x50, 0xa4, 0x33, 0xf5, 0xdd, 0x7d, 0xed, 0xc5, 0x0b, 0xa5, 0x80,
		0x6e, 0xc1, 0x7a, 0xae, 0xbe, 0xb3, 0x6d, 0xb4, 0x5f, 0x69, 0x4a, 0xf1, 0xfe, 0xb7, 0x12, 0xc0,
		0xf8, 0xa5, 0x88, 0xae, 0xc1, 0x72, 0x6b, 0x7f, 0xbb, 0xb3, 0xa7, 0x99, 0xc6, 0xeb, 0x43, 0x2d,
		0x95, 0xc8, 0x32, 0xd4, 0xd2, 0x8a, 0x8e, 0xf6, 0x85, 0x22, 0xa1, 0x55, 0x40, 0x69, 0xe1, 0x6e,
		0x5b, 0xd7, 0x5a, 0x86, 0x52, 0x40, 0x75, 0x58, 0xc9, 0xa2, 0x08, 0x4d, 0x11, 0xad, 0xc3, 0xb5,
		0xb4, 0xe6, 0xa8, 0xd3, 0x3d, 0xd4, 0x5a, 0xed, 0xe7, 0x6d, 0x6d, 0x57, 0x29, 0x6d, 0xfd, 0x52,
		0x84, 0xb2, 0xc1, 0xd8, 0x44, 0x5f, 0x41, 0x35, 0x7b, 0x4f, 0xa0, 0xdb, 0x69, 0xb2, 0x73, 0xef,
		0xb9, 0x86, 0x7a, 0x9e, 0x49, 0x3c, 0x0c, 0xea, 0xcc, 0x27, 0x12, 0xb2, 0x61, 0x69, 0xea, 0x2c,
		0x44, 0x77, 0x26, 0x9c, 0x73, 0xaf, 0x84, 0xc6, 0xdd, 0x0b, 0xac, 0x52, 0x51, 0xfa, 0x80, 0xa6,
		0x37, 0x3a, 0x3a, 0x03, 0x60, 0xe2, 0xc0, 0x6b, 0xfc, 0xff, 0x22, 0xb3, 0x54, 0xa0, 0x80, 0xdf,
		0xfb, 0xd3, 0x1b, 0x00, 0x6d, 0x9e, 0x97, 0x6c, 0x86, 0xb9, 0x7b, 0x97, 0xb0, 0x1c, 0x47, 0xdc,
		0xf9, 0x08, 0xaa, 0x96, 0xef, 0xa6, 0x7c, 0x76, 0x80, 0xb7, 0xed, 0x30, 0xf4, 0xa9, 0x7f, 0x28,
		0x7d, 0x39, 0xc7, 0x85, 0x41, 0xaf, 0x37, 0xcb, 0xff, 0xfd, 0x78, 0xf4, 0x4f, 0x00, 0x00, 0x00,
		0xff, 0xff, 0x33, 0xd6, 0x8b, 0x5c, 0x0c, 0x11, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) TangoYARPCClient {
			return NewTangoYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
