// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: tango.proto

package tangopb

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// TangoYARPCClient is the YARPC client-side interface for the Tango service.
type TangoYARPCClient interface {
	GetTargetGraph(context.Context, *GetTargetGraphRequest, ...yarpc.CallOption) (TangoServiceGetTargetGraphYARPCClient, error)
	GetChangedTargets(context.Context, *GetChangedTargetsRequest, ...yarpc.CallOption) (TangoServiceGetChangedTargetsYARPCClient, error)
	GetChangedServices(context.Context, *GetChangedServicesRequest, ...yarpc.CallOption) (TangoServiceGetChangedServicesYARPCClient, error)
	GetChangedTargetGraph(context.Context, *GetChangedTargetGraphRequest, ...yarpc.CallOption) (TangoServiceGetChangedTargetGraphYARPCClient, error)
}

// TangoServiceGetTargetGraphYARPCClient receives GetTargetGraphResponses, returning io.EOF when the stream is complete.
type TangoServiceGetTargetGraphYARPCClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetTargetGraphResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// TangoServiceGetChangedTargetsYARPCClient receives GetChangedTargetsResponses, returning io.EOF when the stream is complete.
type TangoServiceGetChangedTargetsYARPCClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetChangedTargetsResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// TangoServiceGetChangedServicesYARPCClient receives GetChangedServicesResponses, returning io.EOF when the stream is complete.
type TangoServiceGetChangedServicesYARPCClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetChangedServicesResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

// TangoServiceGetChangedTargetGraphYARPCClient receives GetChangedTargetGraphResponses, returning io.EOF when the stream is complete.
type TangoServiceGetChangedTargetGraphYARPCClient interface {
	Context() context.Context
	Recv(...yarpc.StreamOption) (*GetChangedTargetGraphResponse, error)
	CloseSend(...yarpc.StreamOption) error
}

func newTangoYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) TangoYARPCClient {
	return &_TangoYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.devexp.tango.Tango",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewTangoYARPCClient builds a new YARPC client for the Tango service.
func NewTangoYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) TangoYARPCClient {
	return newTangoYARPCClient(clientConfig, nil, options...)
}

// TangoYARPCServer is the YARPC server-side interface for the Tango service.
type TangoYARPCServer interface {
	GetTargetGraph(*GetTargetGraphRequest, TangoServiceGetTargetGraphYARPCServer) error
	GetChangedTargets(*GetChangedTargetsRequest, TangoServiceGetChangedTargetsYARPCServer) error
	GetChangedServices(*GetChangedServicesRequest, TangoServiceGetChangedServicesYARPCServer) error
	GetChangedTargetGraph(*GetChangedTargetGraphRequest, TangoServiceGetChangedTargetGraphYARPCServer) error
}

// TangoServiceGetTargetGraphYARPCServer sends GetTargetGraphResponses.
type TangoServiceGetTargetGraphYARPCServer interface {
	Context() context.Context
	Send(*GetTargetGraphResponse, ...yarpc.StreamOption) error
}

// TangoServiceGetChangedTargetsYARPCServer sends GetChangedTargetsResponses.
type TangoServiceGetChangedTargetsYARPCServer interface {
	Context() context.Context
	Send(*GetChangedTargetsResponse, ...yarpc.StreamOption) error
}

// TangoServiceGetChangedServicesYARPCServer sends GetChangedServicesResponses.
type TangoServiceGetChangedServicesYARPCServer interface {
	Context() context.Context
	Send(*GetChangedServicesResponse, ...yarpc.StreamOption) error
}

// TangoServiceGetChangedTargetGraphYARPCServer sends GetChangedTargetGraphResponses.
type TangoServiceGetChangedTargetGraphYARPCServer interface {
	Context() context.Context
	Send(*GetChangedTargetGraphResponse, ...yarpc.StreamOption) error
}

type buildTangoYARPCProceduresParams struct {
	Server      TangoYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildTangoYARPCProcedures(params buildTangoYARPCProceduresParams) []transport.Procedure {
	handler := &_TangoYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName:         "uber.devexp.tango.Tango",
			UnaryHandlerParams:  []protobuf.BuildProceduresUnaryHandlerParams{},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{

				{
					MethodName: "GetTargetGraph",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.GetTargetGraph,
						},
					),
				},
				{
					MethodName: "GetChangedTargets",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.GetChangedTargets,
						},
					),
				},
				{
					MethodName: "GetChangedServices",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.GetChangedServices,
						},
					),
				},
				{
					MethodName: "GetChangedTargetGraph",
					Handler: protobuf.NewStreamHandler(
						protobuf.StreamHandlerParams{
							Handle: handler.GetChangedTargetGraph,
						},
					),
				},
			},
		},
	)
}

// BuildTangoYARPCProcedures prepares an implementation of the Tango service for YARPC registration.
func BuildTangoYARPCProcedures(server TangoYARPCServer) []transport.Procedure {
	return buildTangoYARPCProcedures(buildTangoYARPCProceduresParams{Server: server})
}

// FxTangoYARPCClientParams defines the input
// for NewFxTangoYARPCClient. It provides the
// paramaters to get a TangoYARPCClient in an
// Fx application.
type FxTangoYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxTangoYARPCClientResult defines the output
// of NewFxTangoYARPCClient. It provides a
// TangoYARPCClient to an Fx application.
type FxTangoYARPCClientResult struct {
	fx.Out

	Client TangoYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxTangoYARPCClient provides a TangoYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  tangopb.NewFxTangoYARPCClient("service-name"),
//	  ...
//	)
func NewFxTangoYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxTangoYARPCClientParams) FxTangoYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxTangoYARPCClientResult{
			Client: newTangoYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxTangoYARPCProceduresParams defines the input
// for NewFxTangoYARPCProcedures. It provides the
// paramaters to get TangoYARPCServer procedures in an
// Fx application.
type FxTangoYARPCProceduresParams struct {
	fx.In

	Server      TangoYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxTangoYARPCProceduresResult defines the output
// of NewFxTangoYARPCProcedures. It provides
// TangoYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxTangoYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxTangoYARPCProcedures provides TangoYARPCServer procedures to an Fx application.
// It expects a TangoYARPCServer to be present in the container.
//
//	fx.Provide(
//	  tangopb.NewFxTangoYARPCProcedures(),
//	  ...
//	)
func NewFxTangoYARPCProcedures() interface{} {
	return func(params FxTangoYARPCProceduresParams) FxTangoYARPCProceduresResult {
		return FxTangoYARPCProceduresResult{
			Procedures: buildTangoYARPCProcedures(buildTangoYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: TangoReflectionMeta,
		}
	}
}

// TangoReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var TangoReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.devexp.tango.Tango",
	FileDescriptors: yarpcFileDescriptorClosurec4210c857dbeec96,
}

type _TangoYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_TangoYARPCCaller) GetTargetGraph(ctx context.Context, request *GetTargetGraphRequest, options ...yarpc.CallOption) (TangoServiceGetTargetGraphYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "GetTargetGraph", options...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(request); err != nil {
		return nil, err
	}
	return &_TangoServiceGetTargetGraphYARPCClient{stream: stream}, nil
}

func (c *_TangoYARPCCaller) GetChangedTargets(ctx context.Context, request *GetChangedTargetsRequest, options ...yarpc.CallOption) (TangoServiceGetChangedTargetsYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "GetChangedTargets", options...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(request); err != nil {
		return nil, err
	}
	return &_TangoServiceGetChangedTargetsYARPCClient{stream: stream}, nil
}

func (c *_TangoYARPCCaller) GetChangedServices(ctx context.Context, request *GetChangedServicesRequest, options ...yarpc.CallOption) (TangoServiceGetChangedServicesYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "GetChangedServices", options...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(request); err != nil {
		return nil, err
	}
	return &_TangoServiceGetChangedServicesYARPCClient{stream: stream}, nil
}

func (c *_TangoYARPCCaller) GetChangedTargetGraph(ctx context.Context, request *GetChangedTargetGraphRequest, options ...yarpc.CallOption) (TangoServiceGetChangedTargetGraphYARPCClient, error) {
	stream, err := c.streamClient.CallStream(ctx, "GetChangedTargetGraph", options...)
	if err != nil {
		return nil, err
	}
	if err := stream.Send(request); err != nil {
		return nil, err
	}
	return &_TangoServiceGetChangedTargetGraphYARPCClient{stream: stream}, nil
}

type _TangoYARPCHandler struct {
	server TangoYARPCServer
}

func (h *_TangoYARPCHandler) GetTargetGraph(serverStream *protobuf.ServerStream) error {
	requestMessage, err := serverStream.Receive(newTangoServiceGetTargetGraphYARPCRequest)
	if requestMessage == nil {
		return err
	}

	request, ok := requestMessage.(*GetTargetGraphRequest)
	if !ok {
		return protobuf.CastError(emptyTangoServiceGetTargetGraphYARPCRequest, requestMessage)
	}
	return h.server.GetTargetGraph(request, &_TangoServiceGetTargetGraphYARPCServer{serverStream: serverStream})
}

func (h *_TangoYARPCHandler) GetChangedTargets(serverStream *protobuf.ServerStream) error {
	requestMessage, err := serverStream.Receive(newTangoServiceGetChangedTargetsYARPCRequest)
	if requestMessage == nil {
		return err
	}

	request, ok := requestMessage.(*GetChangedTargetsRequest)
	if !ok {
		return protobuf.CastError(emptyTangoServiceGetChangedTargetsYARPCRequest, requestMessage)
	}
	return h.server.GetChangedTargets(request, &_TangoServiceGetChangedTargetsYARPCServer{serverStream: serverStream})
}

func (h *_TangoYARPCHandler) GetChangedServices(serverStream *protobuf.ServerStream) error {
	requestMessage, err := serverStream.Receive(newTangoServiceGetChangedServicesYARPCRequest)
	if requestMessage == nil {
		return err
	}

	request, ok := requestMessage.(*GetChangedServicesRequest)
	if !ok {
		return protobuf.CastError(emptyTangoServiceGetChangedServicesYARPCRequest, requestMessage)
	}
	return h.server.GetChangedServices(request, &_TangoServiceGetChangedServicesYARPCServer{serverStream: serverStream})
}

func (h *_TangoYARPCHandler) GetChangedTargetGraph(serverStream *protobuf.ServerStream) error {
	requestMessage, err := serverStream.Receive(newTangoServiceGetChangedTargetGraphYARPCRequest)
	if requestMessage == nil {
		return err
	}

	request, ok := requestMessage.(*GetChangedTargetGraphRequest)
	if !ok {
		return protobuf.CastError(emptyTangoServiceGetChangedTargetGraphYARPCRequest, requestMessage)
	}
	return h.server.GetChangedTargetGraph(request, &_TangoServiceGetChangedTargetGraphYARPCServer{serverStream: serverStream})
}

type _TangoServiceGetTargetGraphYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_TangoServiceGetTargetGraphYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_TangoServiceGetTargetGraphYARPCClient) Recv(options ...yarpc.StreamOption) (*GetTargetGraphResponse, error) {
	responseMessage, err := c.stream.Receive(newTangoServiceGetTargetGraphYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetTargetGraphResponse)
	if !ok {
		return nil, protobuf.CastError(emptyTangoServiceGetTargetGraphYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_TangoServiceGetTargetGraphYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _TangoServiceGetChangedTargetsYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_TangoServiceGetChangedTargetsYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_TangoServiceGetChangedTargetsYARPCClient) Recv(options ...yarpc.StreamOption) (*GetChangedTargetsResponse, error) {
	responseMessage, err := c.stream.Receive(newTangoServiceGetChangedTargetsYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetChangedTargetsResponse)
	if !ok {
		return nil, protobuf.CastError(emptyTangoServiceGetChangedTargetsYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_TangoServiceGetChangedTargetsYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _TangoServiceGetChangedServicesYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_TangoServiceGetChangedServicesYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_TangoServiceGetChangedServicesYARPCClient) Recv(options ...yarpc.StreamOption) (*GetChangedServicesResponse, error) {
	responseMessage, err := c.stream.Receive(newTangoServiceGetChangedServicesYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetChangedServicesResponse)
	if !ok {
		return nil, protobuf.CastError(emptyTangoServiceGetChangedServicesYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_TangoServiceGetChangedServicesYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _TangoServiceGetChangedTargetGraphYARPCClient struct {
	stream *protobuf.ClientStream
}

func (c *_TangoServiceGetChangedTargetGraphYARPCClient) Context() context.Context {
	return c.stream.Context()
}

func (c *_TangoServiceGetChangedTargetGraphYARPCClient) Recv(options ...yarpc.StreamOption) (*GetChangedTargetGraphResponse, error) {
	responseMessage, err := c.stream.Receive(newTangoServiceGetChangedTargetGraphYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*GetChangedTargetGraphResponse)
	if !ok {
		return nil, protobuf.CastError(emptyTangoServiceGetChangedTargetGraphYARPCResponse, responseMessage)
	}
	return response, err
}

func (c *_TangoServiceGetChangedTargetGraphYARPCClient) CloseSend(options ...yarpc.StreamOption) error {
	return c.stream.Close(options...)
}

type _TangoServiceGetTargetGraphYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_TangoServiceGetTargetGraphYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_TangoServiceGetTargetGraphYARPCServer) Send(response *GetTargetGraphResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

type _TangoServiceGetChangedTargetsYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_TangoServiceGetChangedTargetsYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_TangoServiceGetChangedTargetsYARPCServer) Send(response *GetChangedTargetsResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

type _TangoServiceGetChangedServicesYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_TangoServiceGetChangedServicesYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_TangoServiceGetChangedServicesYARPCServer) Send(response *GetChangedServicesResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

type _TangoServiceGetChangedTargetGraphYARPCServer struct {
	serverStream *protobuf.ServerStream
}

func (s *_TangoServiceGetChangedTargetGraphYARPCServer) Context() context.Context {
	return s.serverStream.Context()
}

func (s *_TangoServiceGetChangedTargetGraphYARPCServer) Send(response *GetChangedTargetGraphResponse, options ...yarpc.StreamOption) error {
	return s.serverStream.Send(response, options...)
}

func newTangoServiceGetTargetGraphYARPCRequest() proto.Message {
	return &GetTargetGraphRequest{}
}

func newTangoServiceGetTargetGraphYARPCResponse() proto.Message {
	return &GetTargetGraphResponse{}
}

func newTangoServiceGetChangedTargetsYARPCRequest() proto.Message {
	return &GetChangedTargetsRequest{}
}

func newTangoServiceGetChangedTargetsYARPCResponse() proto.Message {
	return &GetChangedTargetsResponse{}
}

func newTangoServiceGetChangedServicesYARPCRequest() proto.Message {
	return &GetChangedServicesRequest{}
}

func newTangoServiceGetChangedServicesYARPCResponse() proto.Message {
	return &GetChangedServicesResponse{}
}

func newTangoServiceGetChangedTargetGraphYARPCRequest() proto.Message {
	return &GetChangedTargetGraphRequest{}
}

func newTangoServiceGetChangedTargetGraphYARPCResponse() proto.Message {
	return &GetChangedTargetGraphResponse{}
}

var (
	emptyTangoServiceGetTargetGraphYARPCRequest         = &GetTargetGraphRequest{}
	emptyTangoServiceGetTargetGraphYARPCResponse        = &GetTargetGraphResponse{}
	emptyTangoServiceGetChangedTargetsYARPCRequest      = &GetChangedTargetsRequest{}
	emptyTangoServiceGetChangedTargetsYARPCResponse     = &GetChangedTargetsResponse{}
	emptyTangoServiceGetChangedServicesYARPCRequest     = &GetChangedServicesRequest{}
	emptyTangoServiceGetChangedServicesYARPCResponse    = &GetChangedServicesResponse{}
	emptyTangoServiceGetChangedTargetGraphYARPCRequest  = &GetChangedTargetGraphRequest{}
	emptyTangoServiceGetChangedTargetGraphYARPCResponse = &GetChangedTargetGraphResponse{}
)

var yarpcFileDescriptorClosurec4210c857dbeec96 = [][]byte{
	// tango.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x58, 0x4b, 0x6f, 0xe3, 0xd4,
		0x17, 0xaf, 0xf3, 0x68, 0x93, 0x93, 0x36, 0x49, 0x6f, 0x3b, 0x9d, 0x4c, 0x3a, 0x8f, 0x8c, 0xff,
		0xfa, 0xa3, 0x32, 0xc3, 0x64, 0x46, 0x1d, 0x81, 0x00, 0xcd, 0x80, 0xf2, 0x22, 0x0d, 0x4a, 0xd3,
		0xc8, 0x71, 0x8b, 0x06, 0x90, 0x2c, 0xc7, 0xbe, 0x93, 0x58, 0x93, 0xd8, 0xc6, 0xbe, 0xee, 0x4c,
		0x58, 0x20, 0xb1, 0xe4, 0x1b, 0xb0, 0x60, 0xcd, 0x0a, 0x09, 0xbe, 0x02, 0x1f, 0x82, 0x0d, 0x12,
		0x4b, 0xbe, 0x04, 0x48, 0x08, 0xdd, 0x6b, 0xc7, 0xb1, 0x13, 0xa7, 0x4d, 0x11, 0x0b, 0x04, 0xbb,
		0x7b, 0xcf, 0xe3, 0x77, 0x9e, 0xf7, 0x1c, 0x27, 0x90, 0x21, 0xb2, 0x3e, 0x30, 0xca, 0xa6, 0x65,
		0x10, 0x03, 0x6d, 0x3b, 0x7d, 0x6c, 0x95, 0x55, 0x7c, 0x8e, 0x5f, 0x99, 0x65, 0xc6, 0xe0, 0x1f,
		0xc3, 0x86, 0x80, 0x3f, 0x73, 0xb0, 0x4d, 0x50, 0x1e, 0xe2, 0x8e, 0x35, 0x2a, 0x70, 0x25, 0xee,
		0x20, 0x2d, 0xd0, 0x23, 0xda, 0x83, 0x75, 0xc5, 0x18, 0x8f, 0x35, 0x52, 0x88, 0x31, 0xa2, 0x77,
		0xe3, 0x7f, 0xe4, 0x20, 0x5f, 0x75, 0xb4, 0x91, 0x5a, 0xc7, 0xb6, 0x62, 0x69, 0x26, 0xd1, 0x0c,
		0x9d, 0x0a, 0x5b, 0x78, 0x6c, 0x10, 0xec, 0x21, 0x78, 0x37, 0x74, 0x03, 0x52, 0x7d, 0xd9, 0xc6,
		0x92, 0x3d, 0x94, 0x3d, 0x98, 0x0d, 0x7a, 0xef, 0x0d, 0x65, 0xf4, 0x16, 0xa4, 0x2c, 0xd7, 0xb8,
		0x5d, 0x88, 0x97, 0xe2, 0x07, 0x99, 0xc3, 0x62, 0x79, 0xc1, 0xc5, 0xb2, 0xe7, 0x9f, 0xe0, 0xcb,
		0xa2, 0x2a, 0xa4, 0x6c, 0x62, 0xc9, 0x04, 0x0f, 0x26, 0x85, 0x44, 0x89, 0x3b, 0xc8, 0x1e, 0xbe,
		0x16, 0xa1, 0x57, 0x33, 0xc6, 0xa6, 0x43, 0x64, 0xea, 0x5c, 0xcf, 0x93, 0x16, 0x7c, 0x3d, 0xfe,
		0x5b, 0x0e, 0x36, 0x4f, 0x1c, 0x62, 0x3a, 0xa4, 0x66, 0xe8, 0xcf, 0xb5, 0x01, 0xba, 0x0b, 0x9b,
		0x9a, 0xae, 0x8c, 0x1c, 0x15, 0x4b, 0x44, 0x1e, 0xd8, 0x2c, 0x8a, 0x94, 0x90, 0xf1, 0x68, 0xa2,
		0x3c, 0xb0, 0xd1, 0x03, 0x40, 0x53, 0x11, 0x99, 0x10, 0x4b, 0xeb, 0x3b, 0x04, 0xdb, 0x2c, 0xa8,
		0x94, 0xb0, 0xed, 0x71, 0x2a, 0x3e, 0x03, 0xfd, 0x1f, 0xb2, 0x53, 0xf1, 0xa1, 0x6c, 0x0f, 0x31,
		0x0d, 0x92, 0x8a, 0x6e, 0x79, 0xd4, 0x23, 0x46, 0x44, 0xb7, 0x00, 0x2c, 0xc3, 0x20, 0xb6, 0x64,
		0xe8, 0x23, 0x37, 0x9e, 0x94, 0x90, 0x66, 0x94, 0x13, 0x7d, 0x34, 0xe1, 0x7f, 0x8e, 0x41, 0xee,
		0xc4, 0x24, 0xda, 0x58, 0xfb, 0x1c, 0xab, 0xa2, 0x6c, 0x0d, 0x30, 0x41, 0x59, 0x88, 0x69, 0x2a,
		0xf3, 0x30, 0x29, 0xc4, 0x34, 0x15, 0x21, 0x48, 0x50, 0x0b, 0x5e, 0x7e, 0xd9, 0x19, 0x3d, 0x84,
		0x1d, 0x55, 0xb3, 0xb0, 0x42, 0x24, 0x15, 0x9b, 0x58, 0x57, 0xb1, 0xae, 0x68, 0xd8, 0xcd, 0x73,
		0x52, 0x40, 0x2e, 0xab, 0x1e, 0xe0, 0x50, 0x10, 0x16, 0x78, 0x82, 0x49, 0xb0, 0x33, 0xda, 0x87,
		0xb4, 0xe5, 0x8c, 0xb0, 0x44, 0x26, 0x26, 0x2e, 0x24, 0x99, 0xbd, 0x14, 0x25, 0x88, 0x13, 0x13,
		0x53, 0x05, 0xea, 0x66, 0x61, 0x9d, 0xb9, 0xcc, 0xce, 0xa8, 0x08, 0x29, 0xfc, 0x8a, 0x60, 0x4b,
		0x97, 0x47, 0x85, 0x0d, 0x46, 0xf7, 0xef, 0x48, 0x00, 0x08, 0xa4, 0x2d, 0xc5, 0x0a, 0x7e, 0x18,
		0x51, 0xb8, 0xb9, 0x68, 0xcb, 0xb3, 0x94, 0x36, 0x74, 0x62, 0x4d, 0x84, 0x00, 0x4a, 0xf1, 0x29,
		0xe4, 0xe6, 0xd8, 0xb4, 0x8f, 0x5f, 0xe0, 0x89, 0x97, 0x1d, 0x7a, 0x44, 0xbb, 0x90, 0x3c, 0x97,
		0x47, 0x0e, 0x66, 0xf9, 0x49, 0x0a, 0xee, 0xe5, 0xdd, 0xd8, 0xdb, 0x1c, 0xdf, 0x85, 0xfc, 0x9c,
		0x35, 0x1b, 0x3d, 0x81, 0x0d, 0xe2, 0x1e, 0x0b, 0x1c, 0xf3, 0x91, 0xbf, 0xdc, 0x47, 0x61, 0xaa,
		0xc2, 0x7f, 0x02, 0xd9, 0xda, 0x50, 0xd6, 0x07, 0x33, 0xbc, 0x16, 0xe4, 0x14, 0x97, 0x22, 0x85,
		0x71, 0x4b, 0x51, 0x4d, 0x1b, 0xd4, 0x15, 0xb2, 0x4a, 0x08, 0x8a, 0xff, 0x89, 0x83, 0xad, 0x90,
		0x04, 0x7a, 0x0f, 0x32, 0xae, 0x8c, 0x5b, 0x22, 0x8e, 0xbd, 0x86, 0x5b, 0x4b, 0x81, 0x69, 0xdd,
		0x04, 0x50, 0xfc, 0x33, 0xaa, 0x00, 0x18, 0xa3, 0xa9, 0x63, 0x2c, 0x3f, 0xab, 0xc5, 0x9b, 0x36,
		0x46, 0x53, 0x17, 0x2a, 0x00, 0x3a, 0x7e, 0x39, 0x85, 0x88, 0xaf, 0x0e, 0xa1, 0xe3, 0x97, 0xee,
		0x91, 0xff, 0x75, 0x1d, 0x52, 0xc7, 0x98, 0xc8, 0xaa, 0x4c, 0x64, 0xf4, 0x29, 0x6c, 0xbb, 0x58,
		0x92, 0xa6, 0x4a, 0x63, 0xd9, 0x34, 0x35, 0x7d, 0xe0, 0x65, 0xec, 0x51, 0x04, 0xec, 0x54, 0xaf,
		0xec, 0x62, 0xb5, 0xd4, 0x63, 0x57, 0xc5, 0xed, 0x95, 0x1c, 0x09, 0x53, 0x29, 0xba, 0xdf, 0xd1,
		0x3e, 0x7a, 0xec, 0x72, 0x74, 0xc1, 0xeb, 0xfa, 0x30, 0xba, 0x15, 0xa6, 0xa2, 0x36, 0x1d, 0xb8,
		0x03, 0x1f, 0xd7, 0x1d, 0x6a, 0xf7, 0x2f, 0xf6, 0x7a, 0x10, 0x82, 0x04, 0xe2, 0x13, 0xd0, 0x0b,
		0xd8, 0xf3, 0x5b, 0x5d, 0xd2, 0xe5, 0xf1, 0xcc, 0xe1, 0x04, 0x03, 0x7e, 0xf3, 0x22, 0x60, 0xff,
		0x59, 0x74, 0xe4, 0x71, 0xd8, 0xeb, 0x5d, 0x39, 0x82, 0x85, 0xbe, 0xe4, 0xe0, 0xf6, 0xcc, 0x9a,
		0x4d, 0x2c, 0x4d, 0x1f, 0x48, 0xec, 0xa5, 0xf8, 0x56, 0x93, 0xcc, 0xea, 0x93, 0x95, 0xac, 0xf6,
		0x18, 0xc0, 0x19, 0xd5, 0x0f, 0x19, 0xdf, 0x97, 0x97, 0x4b, 0x14, 0xab, 0xb0, 0x1b, 0x55, 0xc5,
		0xcb, 0x9e, 0x74, 0x3a, 0xf0, 0xa4, 0x29, 0x46, 0x54, 0xad, 0xae, 0x84, 0xf1, 0x14, 0x72, 0x73,
		0x75, 0xb9, 0x92, 0x7a, 0x13, 0x6e, 0x2c, 0xcd, 0xfe, 0x95, 0x80, 0x3a, 0x50, 0xba, 0x2c, 0xa1,
		0x57, 0xc1, 0xe3, 0xbf, 0xe7, 0xe0, 0x5a, 0x13, 0x13, 0x37, 0xc7, 0x4d, 0x4b, 0x36, 0x87, 0xd3,
		0xe5, 0xdf, 0x85, 0xed, 0x3e, 0xdd, 0xe8, 0x92, 0x3a, 0x5b, 0xe9, 0x0c, 0x33, 0x73, 0xf8, 0xbf,
		0x88, 0x7a, 0xcf, 0x6f, 0x7f, 0x21, 0xdf, 0x9f, 0xff, 0x1e, 0xa8, 0xc3, 0x96, 0xc1, 0xf6, 0xab,
		0xa4, 0xb0, 0x05, 0xeb, 0x0d, 0x97, 0x3b, 0x51, 0x93, 0x21, 0xb0, 0x87, 0x85, 0x4d, 0x23, 0x70,
		0xe3, 0xbf, 0xe1, 0x60, 0x6f, 0xde, 0x63, 0xdb, 0x34, 0x74, 0x1b, 0xa3, 0xf7, 0x83, 0x73, 0x7a,
		0x99, 0xa3, 0xf3, 0xd3, 0xfd, 0x68, 0xcd, 0x1f, 0xd5, 0xe8, 0x1d, 0x48, 0x8d, 0xbd, 0xbe, 0xf5,
		0x9c, 0xdb, 0xbf, 0xa0, 0xb5, 0x8f, 0xd6, 0x04, 0x5f, 0xbc, 0xba, 0x0e, 0x09, 0x8d, 0xe0, 0x31,
		0xff, 0x1b, 0x07, 0x85, 0x26, 0x26, 0xe1, 0x89, 0x3f, 0xcd, 0xe9, 0x87, 0x90, 0x7d, 0xae, 0x59,
		0x36, 0x91, 0x2c, 0x7c, 0xae, 0xd9, 0x57, 0x4c, 0xe8, 0x16, 0x53, 0x15, 0x3c, 0x4d, 0xd4, 0x86,
		0x9c, 0x8d, 0x15, 0x43, 0x57, 0x67, 0x60, 0xb1, 0xd5, 0xc1, 0xb2, 0xae, 0xae, 0x8f, 0xb6, 0x50,
		0x9b, 0xf8, 0x5f, 0xa9, 0xcd, 0x77, 0x1c, 0xdc, 0x88, 0x08, 0xde, 0x2b, 0x4f, 0x3b, 0x6a, 0xed,
		0x51, 0x2b, 0x77, 0x2f, 0x5b, 0x7b, 0xb4, 0x48, 0x73, 0x9b, 0xef, 0xef, 0xa8, 0xd5, 0xef, 0x21,
		0x77, 0x7b, 0xd8, 0x3a, 0xd7, 0x14, 0xfc, 0x9f, 0x29, 0x56, 0x1f, 0x8a, 0x51, 0xc1, 0x7b, 0xc5,
		0xba, 0x0b, 0x9b, 0xb6, 0x4b, 0x63, 0x7b, 0xc6, 0xfb, 0x84, 0xcf, 0x78, 0x34, 0x3a, 0xc3, 0xa8,
		0x88, 0xb7, 0x96, 0xa9, 0x84, 0xcd, 0x76, 0x66, 0x5a, 0xc8, 0xb8, 0x34, 0x2a, 0x61, 0xf3, 0x7f,
		0x70, 0x70, 0x73, 0xbe, 0x21, 0x42, 0x53, 0xe6, 0xdf, 0x9e, 0xe4, 0x1f, 0x38, 0xb8, 0xb5, 0x24,
		0x01, 0xff, 0xd0, 0x57, 0x71, 0xef, 0x6b, 0x0e, 0x76, 0x22, 0x7e, 0x29, 0xa1, 0x12, 0xdc, 0xac,
		0x9d, 0x1c, 0x77, 0x4f, 0xc5, 0x8a, 0xd8, 0x3a, 0xe9, 0x48, 0x3d, 0x51, 0xa8, 0x88, 0x8d, 0xe6,
		0x33, 0xa9, 0xd5, 0x39, 0xab, 0xb4, 0x5b, 0xf5, 0xfc, 0x1a, 0xba, 0x0d, 0xc5, 0x48, 0x89, 0xd3,
		0x4e, 0xaf, 0x21, 0xe6, 0xb9, 0xa5, 0xfc, 0xde, 0x51, 0xa3, 0xdd, 0xce, 0xc7, 0xd0, 0x1d, 0xd8,
		0x8f, 0xe4, 0x77, 0x2a, 0x62, 0xeb, 0xac, 0x91, 0x8f, 0xdf, 0xfb, 0x8a, 0x03, 0x98, 0x7d, 0xb6,
		0xa2, 0xeb, 0xb0, 0x53, 0x3b, 0xaa, 0x74, 0x9a, 0x0d, 0x49, 0x7c, 0xd6, 0x6d, 0x04, 0x1c, 0xd9,
		0x81, 0x5c, 0x90, 0xd1, 0x69, 0x7c, 0x94, 0xe7, 0xd0, 0x1e, 0xa0, 0x20, 0xb1, 0xde, 0x12, 0x1a,
		0x35, 0x31, 0x1f, 0x43, 0x05, 0xd8, 0x0d, 0xa3, 0x78, 0x9c, 0x38, 0xda, 0x87, 0xeb, 0x41, 0xce,
		0x69, 0xa7, 0xd7, 0x6d, 0xd4, 0x5a, 0x1f, 0xb4, 0x1a, 0xf5, 0x7c, 0xe2, 0xf0, 0x97, 0x38, 0x24,
		0x45, 0x9a, 0x4d, 0xa4, 0x41, 0x36, 0xbc, 0x90, 0xd0, 0x41, 0x44, 0xce, 0x23, 0xb7, 0x6c, 0xf1,
		0xf5, 0x15, 0x24, 0xdd, 0x46, 0xe1, 0xd7, 0x1e, 0x71, 0xc8, 0x82, 0xed, 0x85, 0xf9, 0x8a, 0xee,
		0x47, 0x63, 0x44, 0xae, 0xa0, 0xe2, 0x1b, 0xab, 0x09, 0x07, 0x6c, 0x3a, 0x80, 0x16, 0xe7, 0x04,
		0xba, 0x18, 0x67, 0x6e, 0x96, 0x16, 0x1f, 0xac, 0x28, 0x1d, 0x30, 0xfb, 0x05, 0xfb, 0x30, 0x59,
		0x7c, 0x38, 0xe8, 0xe1, 0x0a, 0x11, 0x84, 0x72, 0xfc, 0x68, 0x75, 0x85, 0x99, 0xfd, 0x6a, 0x19,
		0xae, 0x29, 0xc6, 0x78, 0x51, 0xb5, 0x0a, 0xac, 0xea, 0x5d, 0xcb, 0x20, 0x46, 0x97, 0xfb, 0x78,
		0x83, 0x11, 0xcd, 0x7e, 0x7f, 0x9d, 0xfd, 0xa3, 0xf2, 0xf8, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff,
		0x13, 0x8f, 0xe6, 0x9f, 0x60, 0x11, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) TangoYARPCClient {
			return NewTangoYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
