// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: tango.proto

package tangopb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Tango_GetTargetGraph_FullMethodName        = "/uber.devexp.tango.Tango/GetTargetGraph"
	Tango_GetChangedTargets_FullMethodName     = "/uber.devexp.tango.Tango/GetChangedTargets"
	Tango_GetChangedServices_FullMethodName    = "/uber.devexp.tango.Tango/GetChangedServices"
	Tango_GetChangedTargetGraph_FullMethodName = "/uber.devexp.tango.Tango/GetChangedTargetGraph"
)

// TangoClient is the client API for Tango service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Tango is the service for analyzing build target graphs and services. It is an abstraction over the underlying build system like Bazel,
// enabling quick understanding of the dependencies between software building blocks and changes across source code revisions.
type TangoClient interface {
	// Return an optimized target graph for a specific state of the Storage
	GetTargetGraph(ctx context.Context, in *GetTargetGraphRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTargetGraphResponse], error)
	// Return a set of targets changed between two revisions
	GetChangedTargets(ctx context.Context, in *GetChangedTargetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChangedTargetsResponse], error)
	// Return a set of changed services between two revisions and their associated Bazel targets
	GetChangedServices(ctx context.Context, in *GetChangedServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChangedServicesResponse], error)
	// Return a full target graph across two revisions with change indicator for each target. It differs from GetChangedTargets in that a full target graph can be constructed for either base or target revision.
	GetChangedTargetGraph(ctx context.Context, in *GetChangedTargetGraphRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChangedTargetGraphResponse], error)
}

type tangoClient struct {
	cc grpc.ClientConnInterface
}

func NewTangoClient(cc grpc.ClientConnInterface) TangoClient {
	return &tangoClient{cc}
}

func (c *tangoClient) GetTargetGraph(ctx context.Context, in *GetTargetGraphRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetTargetGraphResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tango_ServiceDesc.Streams[0], Tango_GetTargetGraph_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetTargetGraphRequest, GetTargetGraphResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tango_GetTargetGraphClient = grpc.ServerStreamingClient[GetTargetGraphResponse]

func (c *tangoClient) GetChangedTargets(ctx context.Context, in *GetChangedTargetsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChangedTargetsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tango_ServiceDesc.Streams[1], Tango_GetChangedTargets_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetChangedTargetsRequest, GetChangedTargetsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tango_GetChangedTargetsClient = grpc.ServerStreamingClient[GetChangedTargetsResponse]

func (c *tangoClient) GetChangedServices(ctx context.Context, in *GetChangedServicesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChangedServicesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tango_ServiceDesc.Streams[2], Tango_GetChangedServices_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetChangedServicesRequest, GetChangedServicesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tango_GetChangedServicesClient = grpc.ServerStreamingClient[GetChangedServicesResponse]

func (c *tangoClient) GetChangedTargetGraph(ctx context.Context, in *GetChangedTargetGraphRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChangedTargetGraphResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Tango_ServiceDesc.Streams[3], Tango_GetChangedTargetGraph_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetChangedTargetGraphRequest, GetChangedTargetGraphResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tango_GetChangedTargetGraphClient = grpc.ServerStreamingClient[GetChangedTargetGraphResponse]

// TangoServer is the server API for Tango service.
// All implementations must embed UnimplementedTangoServer
// for forward compatibility.
//
// Tango is the service for analyzing build target graphs and services. It is an abstraction over the underlying build system like Bazel,
// enabling quick understanding of the dependencies between software building blocks and changes across source code revisions.
type TangoServer interface {
	// Return an optimized target graph for a specific state of the Storage
	GetTargetGraph(*GetTargetGraphRequest, grpc.ServerStreamingServer[GetTargetGraphResponse]) error
	// Return a set of targets changed between two revisions
	GetChangedTargets(*GetChangedTargetsRequest, grpc.ServerStreamingServer[GetChangedTargetsResponse]) error
	// Return a set of changed services between two revisions and their associated Bazel targets
	GetChangedServices(*GetChangedServicesRequest, grpc.ServerStreamingServer[GetChangedServicesResponse]) error
	// Return a full target graph across two revisions with change indicator for each target. It differs from GetChangedTargets in that a full target graph can be constructed for either base or target revision.
	GetChangedTargetGraph(*GetChangedTargetGraphRequest, grpc.ServerStreamingServer[GetChangedTargetGraphResponse]) error
	mustEmbedUnimplementedTangoServer()
}

// UnimplementedTangoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTangoServer struct{}

func (UnimplementedTangoServer) GetTargetGraph(*GetTargetGraphRequest, grpc.ServerStreamingServer[GetTargetGraphResponse]) error {
	return status.Error(codes.Unimplemented, "method GetTargetGraph not implemented")
}
func (UnimplementedTangoServer) GetChangedTargets(*GetChangedTargetsRequest, grpc.ServerStreamingServer[GetChangedTargetsResponse]) error {
	return status.Error(codes.Unimplemented, "method GetChangedTargets not implemented")
}
func (UnimplementedTangoServer) GetChangedServices(*GetChangedServicesRequest, grpc.ServerStreamingServer[GetChangedServicesResponse]) error {
	return status.Error(codes.Unimplemented, "method GetChangedServices not implemented")
}
func (UnimplementedTangoServer) GetChangedTargetGraph(*GetChangedTargetGraphRequest, grpc.ServerStreamingServer[GetChangedTargetGraphResponse]) error {
	return status.Error(codes.Unimplemented, "method GetChangedTargetGraph not implemented")
}
func (UnimplementedTangoServer) mustEmbedUnimplementedTangoServer() {}
func (UnimplementedTangoServer) testEmbeddedByValue()               {}

// UnsafeTangoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TangoServer will
// result in compilation errors.
type UnsafeTangoServer interface {
	mustEmbedUnimplementedTangoServer()
}

func RegisterTangoServer(s grpc.ServiceRegistrar, srv TangoServer) {
	// If the following call panics, it indicates UnimplementedTangoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Tango_ServiceDesc, srv)
}

func _Tango_GetTargetGraph_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetTargetGraphRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TangoServer).GetTargetGraph(m, &grpc.GenericServerStream[GetTargetGraphRequest, GetTargetGraphResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tango_GetTargetGraphServer = grpc.ServerStreamingServer[GetTargetGraphResponse]

func _Tango_GetChangedTargets_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetChangedTargetsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TangoServer).GetChangedTargets(m, &grpc.GenericServerStream[GetChangedTargetsRequest, GetChangedTargetsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tango_GetChangedTargetsServer = grpc.ServerStreamingServer[GetChangedTargetsResponse]

func _Tango_GetChangedServices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetChangedServicesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TangoServer).GetChangedServices(m, &grpc.GenericServerStream[GetChangedServicesRequest, GetChangedServicesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tango_GetChangedServicesServer = grpc.ServerStreamingServer[GetChangedServicesResponse]

func _Tango_GetChangedTargetGraph_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetChangedTargetGraphRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TangoServer).GetChangedTargetGraph(m, &grpc.GenericServerStream[GetChangedTargetGraphRequest, GetChangedTargetGraphResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Tango_GetChangedTargetGraphServer = grpc.ServerStreamingServer[GetChangedTargetGraphResponse]

// Tango_ServiceDesc is the grpc.ServiceDesc for Tango service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tango_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "uber.devexp.tango.Tango",
	HandlerType: (*TangoServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetTargetGraph",
			Handler:       _Tango_GetTargetGraph_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChangedTargets",
			Handler:       _Tango_GetChangedTargets_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChangedServices",
			Handler:       _Tango_GetChangedServices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetChangedTargetGraph",
			Handler:       _Tango_GetChangedTargetGraph_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "tango.proto",
}
