// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: tango.proto

package tangopb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ComputationStrategy controls the computation strategy to use for the target graph
type ComputationStrategy int32

const (
	// A special defaul marker for invalid state
	ComputationStrategy_COMPUTATION_STRATEGY_INVALID ComputationStrategy = 0
	// Computation strategy is not set and should be the default
	ComputationStrategy_COMPUTATION_STRATEGY_UNSET ComputationStrategy = 1
	// Computation strategy uses custom shell commands to compute the initial target graph
	ComputationStrategy_COMPUTATION_STRATEGY_SHELL ComputationStrategy = 2
	// Computation strategy uses native Bazel API to compute the initial target graph
	ComputationStrategy_COMPUTATION_STRATEGY_NATIVE ComputationStrategy = 3
)

// Enum value maps for ComputationStrategy.
var (
	ComputationStrategy_name = map[int32]string{
		0: "COMPUTATION_STRATEGY_INVALID",
		1: "COMPUTATION_STRATEGY_UNSET",
		2: "COMPUTATION_STRATEGY_SHELL",
		3: "COMPUTATION_STRATEGY_NATIVE",
	}
	ComputationStrategy_value = map[string]int32{
		"COMPUTATION_STRATEGY_INVALID": 0,
		"COMPUTATION_STRATEGY_UNSET":   1,
		"COMPUTATION_STRATEGY_SHELL":   2,
		"COMPUTATION_STRATEGY_NATIVE":  3,
	}
)

func (x ComputationStrategy) Enum() *ComputationStrategy {
	p := new(ComputationStrategy)
	*p = x
	return p
}

func (x ComputationStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComputationStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_tango_proto_enumTypes[0].Descriptor()
}

func (ComputationStrategy) Type() protoreflect.EnumType {
	return &file_tango_proto_enumTypes[0]
}

func (x ComputationStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComputationStrategy.Descriptor instead.
func (ComputationStrategy) EnumDescriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{0}
}

// Enum for ChangeType
type ChangeType int32

const (
	ChangeType_CHANGE_TYPE_INVALID     ChangeType = 0
	ChangeType_CHANGE_TYPE_NEW         ChangeType = 1
	ChangeType_CHANGE_TYPE_DIRECT      ChangeType = 2
	ChangeType_CHANGE_TYPE_INDIRECT    ChangeType = 3
	ChangeType_CHANGE_TYPE_UNSPECIFIED ChangeType = 4
)

// Enum value maps for ChangeType.
var (
	ChangeType_name = map[int32]string{
		0: "CHANGE_TYPE_INVALID",
		1: "CHANGE_TYPE_NEW",
		2: "CHANGE_TYPE_DIRECT",
		3: "CHANGE_TYPE_INDIRECT",
		4: "CHANGE_TYPE_UNSPECIFIED",
	}
	ChangeType_value = map[string]int32{
		"CHANGE_TYPE_INVALID":     0,
		"CHANGE_TYPE_NEW":         1,
		"CHANGE_TYPE_DIRECT":      2,
		"CHANGE_TYPE_INDIRECT":    3,
		"CHANGE_TYPE_UNSPECIFIED": 4,
	}
)

func (x ChangeType) Enum() *ChangeType {
	p := new(ChangeType)
	*p = x
	return p
}

func (x ChangeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ChangeType) Descriptor() protoreflect.EnumDescriptor {
	return file_tango_proto_enumTypes[1].Descriptor()
}

func (ChangeType) Type() protoreflect.EnumType {
	return &file_tango_proto_enumTypes[1]
}

func (x ChangeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ChangeType.Descriptor instead.
func (ChangeType) EnumDescriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{1}
}

// BuildDescription defines a Storage state by a primary revision string and
// an optional list of change identifiers (e.g., diff IDs or PR IDs).
type BuildDescription struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The remote of the Storage, like "mobile/android"
	Remote string `protobuf:"bytes,1,opt,name=remote,proto3" json:"remote,omitempty"`
	// The base commit sha of the Storage
	BaseSha string `protobuf:"bytes,2,opt,name=base_sha,json=baseSha,proto3" json:"base_sha,omitempty"`
	// List of change request URLs to apply on top of the base revision.
	// This can be a phabricator diff URL or a github pull request URL.
	// If empty, the computation happens on the base revision.
	RequestUrls []string `protobuf:"bytes,3,rep,name=request_urls,json=requestUrls,proto3" json:"request_urls,omitempty"`
	// The computation strategy of the original target graph
	Strategy      ComputationStrategy `protobuf:"varint,4,opt,name=strategy,proto3,enum=uber.devexp.tango.ComputationStrategy" json:"strategy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildDescription) Reset() {
	*x = BuildDescription{}
	mi := &file_tango_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildDescription) ProtoMessage() {}

func (x *BuildDescription) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildDescription.ProtoReflect.Descriptor instead.
func (*BuildDescription) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{0}
}

func (x *BuildDescription) GetRemote() string {
	if x != nil {
		return x.Remote
	}
	return ""
}

func (x *BuildDescription) GetBaseSha() string {
	if x != nil {
		return x.BaseSha
	}
	return ""
}

func (x *BuildDescription) GetRequestUrls() []string {
	if x != nil {
		return x.RequestUrls
	}
	return nil
}

func (x *BuildDescription) GetStrategy() ComputationStrategy {
	if x != nil {
		return x.Strategy
	}
	return ComputationStrategy_COMPUTATION_STRATEGY_INVALID
}

// OutputConfig controls what payload details are included in responses.
// Some flags may be ignored depending on the specific API.
type OutputConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Indicates if tags should be included in the response
	IncludeTags bool `protobuf:"varint,1,opt,name=include_tags,json=includeTags,proto3" json:"include_tags,omitempty"`
	// Indicates if build target attributes should be included in the response
	IncludeAttributes bool `protobuf:"varint,2,opt,name=include_attributes,json=includeAttributes,proto3" json:"include_attributes,omitempty"`
	// Indicates if hashes should be computed for each target and included in the response
	IncludeHashes bool `protobuf:"varint,3,opt,name=include_hashes,json=includeHashes,proto3" json:"include_hashes,omitempty"`
	// Indicates if only root targets (i.e. targets that are not depended on by any other targets) should be included in the response
	RootsOnly     bool `protobuf:"varint,4,opt,name=roots_only,json=rootsOnly,proto3" json:"roots_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputConfig) Reset() {
	*x = OutputConfig{}
	mi := &file_tango_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputConfig) ProtoMessage() {}

func (x *OutputConfig) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputConfig.ProtoReflect.Descriptor instead.
func (*OutputConfig) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{1}
}

func (x *OutputConfig) GetIncludeTags() bool {
	if x != nil {
		return x.IncludeTags
	}
	return false
}

func (x *OutputConfig) GetIncludeAttributes() bool {
	if x != nil {
		return x.IncludeAttributes
	}
	return false
}

func (x *OutputConfig) GetIncludeHashes() bool {
	if x != nil {
		return x.IncludeHashes
	}
	return false
}

func (x *OutputConfig) GetRootsOnly() bool {
	if x != nil {
		return x.RootsOnly
	}
	return false
}

// OptimizedTarget represents a build target in a compact format with stable numeric identifiers for
// names and dependencies. Optional fields may be omitted based on OutputConfig.
type OptimizedTarget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identifier for the target
	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Hash of the target (optional)
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	// List of IDs representing direct dependencies
	DirectDependencies []int32 `protobuf:"varint,3,rep,packed,name=direct_dependencies,json=directDependencies,proto3" json:"direct_dependencies,omitempty"`
	// List of IDs representing tags (optional)
	Tags []int32 `protobuf:"varint,4,rep,packed,name=tags,proto3" json:"tags,omitempty"`
	// ID representing the rule type (optional)
	RuleType int32 `protobuf:"varint,5,opt,name=rule_type,json=ruleType,proto3" json:"rule_type,omitempty"`
	// Indicates if the target is a root target (optional)
	Root bool `protobuf:"varint,6,opt,name=root,proto3" json:"root,omitempty"`
	// Indicates if the target is external (optional)
	External bool `protobuf:"varint,7,opt,name=external,proto3" json:"external,omitempty"`
	// Map of attribute IDs to values (optional)
	Attributes    map[int32]int32 `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizedTarget) Reset() {
	*x = OptimizedTarget{}
	mi := &file_tango_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizedTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizedTarget) ProtoMessage() {}

func (x *OptimizedTarget) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizedTarget.ProtoReflect.Descriptor instead.
func (*OptimizedTarget) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{2}
}

func (x *OptimizedTarget) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *OptimizedTarget) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *OptimizedTarget) GetDirectDependencies() []int32 {
	if x != nil {
		return x.DirectDependencies
	}
	return nil
}

func (x *OptimizedTarget) GetTags() []int32 {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *OptimizedTarget) GetRuleType() int32 {
	if x != nil {
		return x.RuleType
	}
	return 0
}

func (x *OptimizedTarget) GetRoot() bool {
	if x != nil {
		return x.Root
	}
	return false
}

func (x *OptimizedTarget) GetExternal() bool {
	if x != nil {
		return x.External
	}
	return false
}

func (x *OptimizedTarget) GetAttributes() map[int32]int32 {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// OptimizedTargets represents a set of optimized targets.
type OptimizedTargets struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of optimized targets which are a part of the target graph
	Targets       []*OptimizedTarget `protobuf:"bytes,1,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptimizedTargets) Reset() {
	*x = OptimizedTargets{}
	mi := &file_tango_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptimizedTargets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptimizedTargets) ProtoMessage() {}

func (x *OptimizedTargets) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptimizedTargets.ProtoReflect.Descriptor instead.
func (*OptimizedTargets) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{3}
}

func (x *OptimizedTargets) GetTargets() []*OptimizedTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

// ChangedTargets represents a set of changed targets.
type ChangedTargets struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of changed targets
	ChangedTargets []*ChangedTarget `protobuf:"bytes,1,rep,name=changed_targets,json=changedTargets,proto3" json:"changed_targets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChangedTargets) Reset() {
	*x = ChangedTargets{}
	mi := &file_tango_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedTargets) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedTargets) ProtoMessage() {}

func (x *ChangedTargets) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedTargets.ProtoReflect.Descriptor instead.
func (*ChangedTargets) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{4}
}

func (x *ChangedTargets) GetChangedTargets() []*ChangedTarget {
	if x != nil {
		return x.ChangedTargets
	}
	return nil
}

// ChangedTarget represents a changed target and its associated optimized targets.
type ChangedTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChangeType    ChangeType             `protobuf:"varint,1,opt,name=change_type,json=changeType,proto3,enum=uber.devexp.tango.ChangeType" json:"change_type,omitempty"` // Type of the change
	OldTarget     *OptimizedTarget       `protobuf:"bytes,2,opt,name=old_target,json=oldTarget,proto3" json:"old_target,omitempty"`                                       // The old target before the change (first revision)
	NewTarget     *OptimizedTarget       `protobuf:"bytes,3,opt,name=new_target,json=newTarget,proto3" json:"new_target,omitempty"`                                       // The new target after the change (second revision)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangedTarget) Reset() {
	*x = ChangedTarget{}
	mi := &file_tango_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangedTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangedTarget) ProtoMessage() {}

func (x *ChangedTarget) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangedTarget.ProtoReflect.Descriptor instead.
func (*ChangedTarget) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{5}
}

func (x *ChangedTarget) GetChangeType() ChangeType {
	if x != nil {
		return x.ChangeType
	}
	return ChangeType_CHANGE_TYPE_INVALID
}

func (x *ChangedTarget) GetOldTarget() *OptimizedTarget {
	if x != nil {
		return x.OldTarget
	}
	return nil
}

func (x *ChangedTarget) GetNewTarget() *OptimizedTarget {
	if x != nil {
		return x.NewTarget
	}
	return nil
}

// Metadata emitted as the last stream item to provide id->name mappings, etc.
type Metadata struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Map of target IDs to names
	TargetIdMapping map[int32]string `protobuf:"bytes,1,rep,name=target_id_mapping,json=targetIdMapping,proto3" json:"target_id_mapping,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Map of rule type IDs to names
	RuleTypeMapping map[int32]string `protobuf:"bytes,2,rep,name=rule_type_mapping,json=ruleTypeMapping,proto3" json:"rule_type_mapping,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Map of tag IDs to names
	TagMapping map[int32]string `protobuf:"bytes,3,rep,name=tag_mapping,json=tagMapping,proto3" json:"tag_mapping,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Map of attribute name IDs to names
	AttributeNameMapping map[int32]string `protobuf:"bytes,4,rep,name=attribute_name_mapping,json=attributeNameMapping,proto3" json:"attribute_name_mapping,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Map of attribute string value IDs to names
	AttributeStringValueMapping map[int32]string `protobuf:"bytes,5,rep,name=attribute_string_value_mapping,json=attributeStringValueMapping,proto3" json:"attribute_string_value_mapping,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_tango_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{6}
}

func (x *Metadata) GetTargetIdMapping() map[int32]string {
	if x != nil {
		return x.TargetIdMapping
	}
	return nil
}

func (x *Metadata) GetRuleTypeMapping() map[int32]string {
	if x != nil {
		return x.RuleTypeMapping
	}
	return nil
}

func (x *Metadata) GetTagMapping() map[int32]string {
	if x != nil {
		return x.TagMapping
	}
	return nil
}

func (x *Metadata) GetAttributeNameMapping() map[int32]string {
	if x != nil {
		return x.AttributeNameMapping
	}
	return nil
}

func (x *Metadata) GetAttributeStringValueMapping() map[int32]string {
	if x != nil {
		return x.AttributeStringValueMapping
	}
	return nil
}

// GetTargetGraphRequest is the request for the GetTargetGraph method, contaions the state of the Storage to analyze.
type GetTargetGraphRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The Storage state to analyze
	BuildDescription *BuildDescription `protobuf:"bytes,1,opt,name=build_description,json=buildDescription,proto3" json:"build_description,omitempty"`
	// Controls what payload details are included in responses; used to reduce payload size when full attribute set is not needed
	OutputConfig  *OutputConfig `protobuf:"bytes,2,opt,name=output_config,json=outputConfig,proto3" json:"output_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetGraphRequest) Reset() {
	*x = GetTargetGraphRequest{}
	mi := &file_tango_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetGraphRequest) ProtoMessage() {}

func (x *GetTargetGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetGraphRequest.ProtoReflect.Descriptor instead.
func (*GetTargetGraphRequest) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{7}
}

func (x *GetTargetGraphRequest) GetBuildDescription() *BuildDescription {
	if x != nil {
		return x.BuildDescription
	}
	return nil
}

func (x *GetTargetGraphRequest) GetOutputConfig() *OutputConfig {
	if x != nil {
		return x.OutputConfig
	}
	return nil
}

// GetTargetGraphResponse is a stream response for the GetTargetGraph method.
// It begins with a stream of optimized targets representing the target graph and metadata is the last item in the payload.
type GetTargetGraphResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*GetTargetGraphResponse_Targets
	//	*GetTargetGraphResponse_Metadata
	Item          isGetTargetGraphResponse_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTargetGraphResponse) Reset() {
	*x = GetTargetGraphResponse{}
	mi := &file_tango_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTargetGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTargetGraphResponse) ProtoMessage() {}

func (x *GetTargetGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTargetGraphResponse.ProtoReflect.Descriptor instead.
func (*GetTargetGraphResponse) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{8}
}

func (x *GetTargetGraphResponse) GetItem() isGetTargetGraphResponse_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetTargetGraphResponse) GetTargets() *OptimizedTargets {
	if x != nil {
		if x, ok := x.Item.(*GetTargetGraphResponse_Targets); ok {
			return x.Targets
		}
	}
	return nil
}

func (x *GetTargetGraphResponse) GetMetadata() *Metadata {
	if x != nil {
		if x, ok := x.Item.(*GetTargetGraphResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

type isGetTargetGraphResponse_Item interface {
	isGetTargetGraphResponse_Item()
}

type GetTargetGraphResponse_Targets struct {
	// Optimized targets representing the target graph in a compact format
	Targets *OptimizedTargets `protobuf:"bytes,1,opt,name=targets,proto3,oneof"`
}

type GetTargetGraphResponse_Metadata struct {
	// Metadata is the last item in the payload and contains id->name mappings, etc.
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3,oneof"`
}

func (*GetTargetGraphResponse_Targets) isGetTargetGraphResponse_Item() {}

func (*GetTargetGraphResponse_Metadata) isGetTargetGraphResponse_Item() {}

// GetChangedTargetsRequest is the request for the GetChangedTargets method, contains the state of the Storage to analyze.
// Changed targets between base and target revisions are returned.
type GetChangedTargetsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The first revision spec
	FirstRevision *BuildDescription `protobuf:"bytes,1,opt,name=first_revision,json=firstRevision,proto3" json:"first_revision,omitempty"`
	// The second revision spec
	SecondRevision *BuildDescription `protobuf:"bytes,2,opt,name=second_revision,json=secondRevision,proto3" json:"second_revision,omitempty"`
	// Controls what payload details are included in responses; used to reduce payload size when full attribute set is not needed
	OutputConfig  *OutputConfig `protobuf:"bytes,3,opt,name=output_config,json=outputConfig,proto3" json:"output_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChangedTargetsRequest) Reset() {
	*x = GetChangedTargetsRequest{}
	mi := &file_tango_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangedTargetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangedTargetsRequest) ProtoMessage() {}

func (x *GetChangedTargetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangedTargetsRequest.ProtoReflect.Descriptor instead.
func (*GetChangedTargetsRequest) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{9}
}

func (x *GetChangedTargetsRequest) GetFirstRevision() *BuildDescription {
	if x != nil {
		return x.FirstRevision
	}
	return nil
}

func (x *GetChangedTargetsRequest) GetSecondRevision() *BuildDescription {
	if x != nil {
		return x.SecondRevision
	}
	return nil
}

func (x *GetChangedTargetsRequest) GetOutputConfig() *OutputConfig {
	if x != nil {
		return x.OutputConfig
	}
	return nil
}

// GetChangedTargetsResponse is the response for the GetChangedTargets method.
// It begins with a stream of targets with their change type and metadata is the last item in the payload.
type GetChangedTargetsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*GetChangedTargetsResponse_ChangedTargets
	//	*GetChangedTargetsResponse_Metadata
	Item          isGetChangedTargetsResponse_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChangedTargetsResponse) Reset() {
	*x = GetChangedTargetsResponse{}
	mi := &file_tango_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangedTargetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangedTargetsResponse) ProtoMessage() {}

func (x *GetChangedTargetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangedTargetsResponse.ProtoReflect.Descriptor instead.
func (*GetChangedTargetsResponse) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{10}
}

func (x *GetChangedTargetsResponse) GetItem() isGetChangedTargetsResponse_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetChangedTargetsResponse) GetChangedTargets() *ChangedTargets {
	if x != nil {
		if x, ok := x.Item.(*GetChangedTargetsResponse_ChangedTargets); ok {
			return x.ChangedTargets
		}
	}
	return nil
}

func (x *GetChangedTargetsResponse) GetMetadata() *Metadata {
	if x != nil {
		if x, ok := x.Item.(*GetChangedTargetsResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

type isGetChangedTargetsResponse_Item interface {
	isGetChangedTargetsResponse_Item()
}

type GetChangedTargetsResponse_ChangedTargets struct {
	// A packet with optimized targets representing a portion of the target graph; all such packets represent the full target graph
	ChangedTargets *ChangedTargets `protobuf:"bytes,1,opt,name=changed_targets,json=changedTargets,proto3,oneof"`
}

type GetChangedTargetsResponse_Metadata struct {
	// Metadata is the last item in the payload and contains id->name mappings, etc. and used to reconstruct the full target graph with literal target names
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3,oneof"`
}

func (*GetChangedTargetsResponse_ChangedTargets) isGetChangedTargetsResponse_Item() {}

func (*GetChangedTargetsResponse_Metadata) isGetChangedTargetsResponse_Item() {}

// GetChangedServicesRequest is the request for the GetChangedServices method, contains the state of the Storage to analyze.
// Changed services between base and target revisions are returned.
type GetChangedServicesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The base revision spec
	FirstRevision *BuildDescription `protobuf:"bytes,1,opt,name=first_revision,json=firstRevision,proto3" json:"first_revision,omitempty"`
	// The target revision spec
	SecondRevision *BuildDescription `protobuf:"bytes,2,opt,name=second_revision,json=secondRevision,proto3" json:"second_revision,omitempty"`
	// Controls what payload details are included in responses; used to reduce payload size when full attribute set is not needed
	OutputConfig  *OutputConfig `protobuf:"bytes,3,opt,name=output_config,json=outputConfig,proto3" json:"output_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChangedServicesRequest) Reset() {
	*x = GetChangedServicesRequest{}
	mi := &file_tango_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangedServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangedServicesRequest) ProtoMessage() {}

func (x *GetChangedServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangedServicesRequest.ProtoReflect.Descriptor instead.
func (*GetChangedServicesRequest) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{11}
}

func (x *GetChangedServicesRequest) GetFirstRevision() *BuildDescription {
	if x != nil {
		return x.FirstRevision
	}
	return nil
}

func (x *GetChangedServicesRequest) GetSecondRevision() *BuildDescription {
	if x != nil {
		return x.SecondRevision
	}
	return nil
}

func (x *GetChangedServicesRequest) GetOutputConfig() *OutputConfig {
	if x != nil {
		return x.OutputConfig
	}
	return nil
}

// ChangedService represents a changed service and its associated Bazel targets.
type GetChangedServicesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the changed service
	ServiceName string `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	// Literal full names of the changed targets belonging to the service
	TargetNames   []string `protobuf:"bytes,2,rep,name=target_names,json=targetNames,proto3" json:"target_names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChangedServicesResponse) Reset() {
	*x = GetChangedServicesResponse{}
	mi := &file_tango_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangedServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangedServicesResponse) ProtoMessage() {}

func (x *GetChangedServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangedServicesResponse.ProtoReflect.Descriptor instead.
func (*GetChangedServicesResponse) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{12}
}

func (x *GetChangedServicesResponse) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *GetChangedServicesResponse) GetTargetNames() []string {
	if x != nil {
		return x.TargetNames
	}
	return nil
}

// GetChangedTargetGraphRequest is the request for the GetChangedTargetGraph method, contains the state of the Storage to analyze.
// Changed target graph between base and target revisions are returned.
type GetChangedTargetGraphRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The base revision spec
	FirstRevision *BuildDescription `protobuf:"bytes,1,opt,name=first_revision,json=firstRevision,proto3" json:"first_revision,omitempty"`
	// The target revision spec
	SecondRevision *BuildDescription `protobuf:"bytes,2,opt,name=second_revision,json=secondRevision,proto3" json:"second_revision,omitempty"`
	// Controls what payload details are included in responses; used to reduce payload size when full attribute set is not needed
	OutputConfig  *OutputConfig `protobuf:"bytes,3,opt,name=output_config,json=outputConfig,proto3" json:"output_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChangedTargetGraphRequest) Reset() {
	*x = GetChangedTargetGraphRequest{}
	mi := &file_tango_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangedTargetGraphRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangedTargetGraphRequest) ProtoMessage() {}

func (x *GetChangedTargetGraphRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangedTargetGraphRequest.ProtoReflect.Descriptor instead.
func (*GetChangedTargetGraphRequest) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{13}
}

func (x *GetChangedTargetGraphRequest) GetFirstRevision() *BuildDescription {
	if x != nil {
		return x.FirstRevision
	}
	return nil
}

func (x *GetChangedTargetGraphRequest) GetSecondRevision() *BuildDescription {
	if x != nil {
		return x.SecondRevision
	}
	return nil
}

func (x *GetChangedTargetGraphRequest) GetOutputConfig() *OutputConfig {
	if x != nil {
		return x.OutputConfig
	}
	return nil
}

// GetChangedTargetGraphResponse is the response for the GetChangedTargetGraph method.
// It begins with a stream of targets with their change type and metadata is the last item in the payload.
type GetChangedTargetGraphResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Item:
	//
	//	*GetChangedTargetGraphResponse_ChangedTargets
	//	*GetChangedTargetGraphResponse_Metadata
	Item          isGetChangedTargetGraphResponse_Item `protobuf_oneof:"item"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChangedTargetGraphResponse) Reset() {
	*x = GetChangedTargetGraphResponse{}
	mi := &file_tango_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChangedTargetGraphResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChangedTargetGraphResponse) ProtoMessage() {}

func (x *GetChangedTargetGraphResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tango_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChangedTargetGraphResponse.ProtoReflect.Descriptor instead.
func (*GetChangedTargetGraphResponse) Descriptor() ([]byte, []int) {
	return file_tango_proto_rawDescGZIP(), []int{14}
}

func (x *GetChangedTargetGraphResponse) GetItem() isGetChangedTargetGraphResponse_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetChangedTargetGraphResponse) GetChangedTargets() *ChangedTargets {
	if x != nil {
		if x, ok := x.Item.(*GetChangedTargetGraphResponse_ChangedTargets); ok {
			return x.ChangedTargets
		}
	}
	return nil
}

func (x *GetChangedTargetGraphResponse) GetMetadata() *Metadata {
	if x != nil {
		if x, ok := x.Item.(*GetChangedTargetGraphResponse_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

type isGetChangedTargetGraphResponse_Item interface {
	isGetChangedTargetGraphResponse_Item()
}

type GetChangedTargetGraphResponse_ChangedTargets struct {
	// A packet with optimized targets representing a portion of the target graph; all such packets represent the full target graph
	ChangedTargets *ChangedTargets `protobuf:"bytes,1,opt,name=changed_targets,json=changedTargets,proto3,oneof"`
}

type GetChangedTargetGraphResponse_Metadata struct {
	// Metadata is the last item in the payload and contains id->name mappings, etc. and used to reconstruct the full target graph with literal target names
	Metadata *Metadata `protobuf:"bytes,2,opt,name=metadata,proto3,oneof"`
}

func (*GetChangedTargetGraphResponse_ChangedTargets) isGetChangedTargetGraphResponse_Item() {}

func (*GetChangedTargetGraphResponse_Metadata) isGetChangedTargetGraphResponse_Item() {}

var File_tango_proto protoreflect.FileDescriptor

const file_tango_proto_rawDesc = "" +
	"\n" +
	"\vtango.proto\x12\x11uber.devexp.tango\"\xac\x01\n" +
	"\x10BuildDescription\x12\x16\n" +
	"\x06remote\x18\x01 \x01(\tR\x06remote\x12\x19\n" +
	"\bbase_sha\x18\x02 \x01(\tR\abaseSha\x12!\n" +
	"\frequest_urls\x18\x03 \x03(\tR\vrequestUrls\x12B\n" +
	"\bstrategy\x18\x04 \x01(\x0e2&.uber.devexp.tango.ComputationStrategyR\bstrategy\"\xa6\x01\n" +
	"\fOutputConfig\x12!\n" +
	"\finclude_tags\x18\x01 \x01(\bR\vincludeTags\x12-\n" +
	"\x12include_attributes\x18\x02 \x01(\bR\x11includeAttributes\x12%\n" +
	"\x0einclude_hashes\x18\x03 \x01(\bR\rincludeHashes\x12\x1d\n" +
	"\n" +
	"roots_only\x18\x04 \x01(\bR\trootsOnly\"\xda\x02\n" +
	"\x0fOptimizedTarget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\tR\x04hash\x12/\n" +
	"\x13direct_dependencies\x18\x03 \x03(\x05R\x12directDependencies\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\x05R\x04tags\x12\x1b\n" +
	"\trule_type\x18\x05 \x01(\x05R\bruleType\x12\x12\n" +
	"\x04root\x18\x06 \x01(\bR\x04root\x12\x1a\n" +
	"\bexternal\x18\a \x01(\bR\bexternal\x12R\n" +
	"\n" +
	"attributes\x18\b \x03(\v22.uber.devexp.tango.OptimizedTarget.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"P\n" +
	"\x10OptimizedTargets\x12<\n" +
	"\atargets\x18\x01 \x03(\v2\".uber.devexp.tango.OptimizedTargetR\atargets\"[\n" +
	"\x0eChangedTargets\x12I\n" +
	"\x0fchanged_targets\x18\x01 \x03(\v2 .uber.devexp.tango.ChangedTargetR\x0echangedTargets\"\xd5\x01\n" +
	"\rChangedTarget\x12>\n" +
	"\vchange_type\x18\x01 \x01(\x0e2\x1d.uber.devexp.tango.ChangeTypeR\n" +
	"changeType\x12A\n" +
	"\n" +
	"old_target\x18\x02 \x01(\v2\".uber.devexp.tango.OptimizedTargetR\toldTarget\x12A\n" +
	"\n" +
	"new_target\x18\x03 \x01(\v2\".uber.devexp.tango.OptimizedTargetR\tnewTarget\"\xe5\x06\n" +
	"\bMetadata\x12\\\n" +
	"\x11target_id_mapping\x18\x01 \x03(\v20.uber.devexp.tango.Metadata.TargetIdMappingEntryR\x0ftargetIdMapping\x12\\\n" +
	"\x11rule_type_mapping\x18\x02 \x03(\v20.uber.devexp.tango.Metadata.RuleTypeMappingEntryR\x0fruleTypeMapping\x12L\n" +
	"\vtag_mapping\x18\x03 \x03(\v2+.uber.devexp.tango.Metadata.TagMappingEntryR\n" +
	"tagMapping\x12k\n" +
	"\x16attribute_name_mapping\x18\x04 \x03(\v25.uber.devexp.tango.Metadata.AttributeNameMappingEntryR\x14attributeNameMapping\x12\x81\x01\n" +
	"\x1eattribute_string_value_mapping\x18\x05 \x03(\v2<.uber.devexp.tango.Metadata.AttributeStringValueMappingEntryR\x1battributeStringValueMapping\x1aB\n" +
	"\x14TargetIdMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aB\n" +
	"\x14RuleTypeMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fTagMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aG\n" +
	"\x19AttributeNameMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aN\n" +
	" AttributeStringValueMappingEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x05R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xaf\x01\n" +
	"\x15GetTargetGraphRequest\x12P\n" +
	"\x11build_description\x18\x01 \x01(\v2#.uber.devexp.tango.BuildDescriptionR\x10buildDescription\x12D\n" +
	"\routput_config\x18\x02 \x01(\v2\x1f.uber.devexp.tango.OutputConfigR\foutputConfig\"\x9c\x01\n" +
	"\x16GetTargetGraphResponse\x12?\n" +
	"\atargets\x18\x01 \x01(\v2#.uber.devexp.tango.OptimizedTargetsH\x00R\atargets\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.uber.devexp.tango.MetadataH\x00R\bmetadataB\x06\n" +
	"\x04item\"\xfa\x01\n" +
	"\x18GetChangedTargetsRequest\x12J\n" +
	"\x0efirst_revision\x18\x01 \x01(\v2#.uber.devexp.tango.BuildDescriptionR\rfirstRevision\x12L\n" +
	"\x0fsecond_revision\x18\x02 \x01(\v2#.uber.devexp.tango.BuildDescriptionR\x0esecondRevision\x12D\n" +
	"\routput_config\x18\x03 \x01(\v2\x1f.uber.devexp.tango.OutputConfigR\foutputConfig\"\xac\x01\n" +
	"\x19GetChangedTargetsResponse\x12L\n" +
	"\x0fchanged_targets\x18\x01 \x01(\v2!.uber.devexp.tango.ChangedTargetsH\x00R\x0echangedTargets\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.uber.devexp.tango.MetadataH\x00R\bmetadataB\x06\n" +
	"\x04item\"\xfb\x01\n" +
	"\x19GetChangedServicesRequest\x12J\n" +
	"\x0efirst_revision\x18\x01 \x01(\v2#.uber.devexp.tango.BuildDescriptionR\rfirstRevision\x12L\n" +
	"\x0fsecond_revision\x18\x02 \x01(\v2#.uber.devexp.tango.BuildDescriptionR\x0esecondRevision\x12D\n" +
	"\routput_config\x18\x03 \x01(\v2\x1f.uber.devexp.tango.OutputConfigR\foutputConfig\"b\n" +
	"\x1aGetChangedServicesResponse\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12!\n" +
	"\ftarget_names\x18\x02 \x03(\tR\vtargetNames\"\xfe\x01\n" +
	"\x1cGetChangedTargetGraphRequest\x12J\n" +
	"\x0efirst_revision\x18\x01 \x01(\v2#.uber.devexp.tango.BuildDescriptionR\rfirstRevision\x12L\n" +
	"\x0fsecond_revision\x18\x02 \x01(\v2#.uber.devexp.tango.BuildDescriptionR\x0esecondRevision\x12D\n" +
	"\routput_config\x18\x03 \x01(\v2\x1f.uber.devexp.tango.OutputConfigR\foutputConfig\"\xb0\x01\n" +
	"\x1dGetChangedTargetGraphResponse\x12L\n" +
	"\x0fchanged_targets\x18\x01 \x01(\v2!.uber.devexp.tango.ChangedTargetsH\x00R\x0echangedTargets\x129\n" +
	"\bmetadata\x18\x02 \x01(\v2\x1b.uber.devexp.tango.MetadataH\x00R\bmetadataB\x06\n" +
	"\x04item*\x98\x01\n" +
	"\x13ComputationStrategy\x12 \n" +
	"\x1cCOMPUTATION_STRATEGY_INVALID\x10\x00\x12\x1e\n" +
	"\x1aCOMPUTATION_STRATEGY_UNSET\x10\x01\x12\x1e\n" +
	"\x1aCOMPUTATION_STRATEGY_SHELL\x10\x02\x12\x1f\n" +
	"\x1bCOMPUTATION_STRATEGY_NATIVE\x10\x03*\x89\x01\n" +
	"\n" +
	"ChangeType\x12\x17\n" +
	"\x13CHANGE_TYPE_INVALID\x10\x00\x12\x13\n" +
	"\x0fCHANGE_TYPE_NEW\x10\x01\x12\x16\n" +
	"\x12CHANGE_TYPE_DIRECT\x10\x02\x12\x18\n" +
	"\x14CHANGE_TYPE_INDIRECT\x10\x03\x12\x1b\n" +
	"\x17CHANGE_TYPE_UNSPECIFIED\x10\x042\xdd\x03\n" +
	"\x05Tango\x12i\n" +
	"\x0eGetTargetGraph\x12(.uber.devexp.tango.GetTargetGraphRequest\x1a).uber.devexp.tango.GetTargetGraphResponse\"\x000\x01\x12r\n" +
	"\x11GetChangedTargets\x12+.uber.devexp.tango.GetChangedTargetsRequest\x1a,.uber.devexp.tango.GetChangedTargetsResponse\"\x000\x01\x12u\n" +
	"\x12GetChangedServices\x12,.uber.devexp.tango.GetChangedServicesRequest\x1a-.uber.devexp.tango.GetChangedServicesResponse\"\x000\x01\x12~\n" +
	"\x15GetChangedTargetGraph\x12/.uber.devexp.tango.GetChangedTargetGraphRequest\x1a0.uber.devexp.tango.GetChangedTargetGraphResponse\"\x000\x01BL\n" +
	"\x15com.uber.devexp.tangoB\n" +
	"TangoProtoP\x01Z%github.com/uber/tango/tangopb;tangopbb\x06proto3"

var (
	file_tango_proto_rawDescOnce sync.Once
	file_tango_proto_rawDescData []byte
)

func file_tango_proto_rawDescGZIP() []byte {
	file_tango_proto_rawDescOnce.Do(func() {
		file_tango_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tango_proto_rawDesc), len(file_tango_proto_rawDesc)))
	})
	return file_tango_proto_rawDescData
}

var file_tango_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tango_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_tango_proto_goTypes = []any{
	(ComputationStrategy)(0),              // 0: uber.devexp.tango.ComputationStrategy
	(ChangeType)(0),                       // 1: uber.devexp.tango.ChangeType
	(*BuildDescription)(nil),              // 2: uber.devexp.tango.BuildDescription
	(*OutputConfig)(nil),                  // 3: uber.devexp.tango.OutputConfig
	(*OptimizedTarget)(nil),               // 4: uber.devexp.tango.OptimizedTarget
	(*OptimizedTargets)(nil),              // 5: uber.devexp.tango.OptimizedTargets
	(*ChangedTargets)(nil),                // 6: uber.devexp.tango.ChangedTargets
	(*ChangedTarget)(nil),                 // 7: uber.devexp.tango.ChangedTarget
	(*Metadata)(nil),                      // 8: uber.devexp.tango.Metadata
	(*GetTargetGraphRequest)(nil),         // 9: uber.devexp.tango.GetTargetGraphRequest
	(*GetTargetGraphResponse)(nil),        // 10: uber.devexp.tango.GetTargetGraphResponse
	(*GetChangedTargetsRequest)(nil),      // 11: uber.devexp.tango.GetChangedTargetsRequest
	(*GetChangedTargetsResponse)(nil),     // 12: uber.devexp.tango.GetChangedTargetsResponse
	(*GetChangedServicesRequest)(nil),     // 13: uber.devexp.tango.GetChangedServicesRequest
	(*GetChangedServicesResponse)(nil),    // 14: uber.devexp.tango.GetChangedServicesResponse
	(*GetChangedTargetGraphRequest)(nil),  // 15: uber.devexp.tango.GetChangedTargetGraphRequest
	(*GetChangedTargetGraphResponse)(nil), // 16: uber.devexp.tango.GetChangedTargetGraphResponse
	nil,                                   // 17: uber.devexp.tango.OptimizedTarget.AttributesEntry
	nil,                                   // 18: uber.devexp.tango.Metadata.TargetIdMappingEntry
	nil,                                   // 19: uber.devexp.tango.Metadata.RuleTypeMappingEntry
	nil,                                   // 20: uber.devexp.tango.Metadata.TagMappingEntry
	nil,                                   // 21: uber.devexp.tango.Metadata.AttributeNameMappingEntry
	nil,                                   // 22: uber.devexp.tango.Metadata.AttributeStringValueMappingEntry
}
var file_tango_proto_depIdxs = []int32{
	0,  // 0: uber.devexp.tango.BuildDescription.strategy:type_name -> uber.devexp.tango.ComputationStrategy
	17, // 1: uber.devexp.tango.OptimizedTarget.attributes:type_name -> uber.devexp.tango.OptimizedTarget.AttributesEntry
	4,  // 2: uber.devexp.tango.OptimizedTargets.targets:type_name -> uber.devexp.tango.OptimizedTarget
	7,  // 3: uber.devexp.tango.ChangedTargets.changed_targets:type_name -> uber.devexp.tango.ChangedTarget
	1,  // 4: uber.devexp.tango.ChangedTarget.change_type:type_name -> uber.devexp.tango.ChangeType
	4,  // 5: uber.devexp.tango.ChangedTarget.old_target:type_name -> uber.devexp.tango.OptimizedTarget
	4,  // 6: uber.devexp.tango.ChangedTarget.new_target:type_name -> uber.devexp.tango.OptimizedTarget
	18, // 7: uber.devexp.tango.Metadata.target_id_mapping:type_name -> uber.devexp.tango.Metadata.TargetIdMappingEntry
	19, // 8: uber.devexp.tango.Metadata.rule_type_mapping:type_name -> uber.devexp.tango.Metadata.RuleTypeMappingEntry
	20, // 9: uber.devexp.tango.Metadata.tag_mapping:type_name -> uber.devexp.tango.Metadata.TagMappingEntry
	21, // 10: uber.devexp.tango.Metadata.attribute_name_mapping:type_name -> uber.devexp.tango.Metadata.AttributeNameMappingEntry
	22, // 11: uber.devexp.tango.Metadata.attribute_string_value_mapping:type_name -> uber.devexp.tango.Metadata.AttributeStringValueMappingEntry
	2,  // 12: uber.devexp.tango.GetTargetGraphRequest.build_description:type_name -> uber.devexp.tango.BuildDescription
	3,  // 13: uber.devexp.tango.GetTargetGraphRequest.output_config:type_name -> uber.devexp.tango.OutputConfig
	5,  // 14: uber.devexp.tango.GetTargetGraphResponse.targets:type_name -> uber.devexp.tango.OptimizedTargets
	8,  // 15: uber.devexp.tango.GetTargetGraphResponse.metadata:type_name -> uber.devexp.tango.Metadata
	2,  // 16: uber.devexp.tango.GetChangedTargetsRequest.first_revision:type_name -> uber.devexp.tango.BuildDescription
	2,  // 17: uber.devexp.tango.GetChangedTargetsRequest.second_revision:type_name -> uber.devexp.tango.BuildDescription
	3,  // 18: uber.devexp.tango.GetChangedTargetsRequest.output_config:type_name -> uber.devexp.tango.OutputConfig
	6,  // 19: uber.devexp.tango.GetChangedTargetsResponse.changed_targets:type_name -> uber.devexp.tango.ChangedTargets
	8,  // 20: uber.devexp.tango.GetChangedTargetsResponse.metadata:type_name -> uber.devexp.tango.Metadata
	2,  // 21: uber.devexp.tango.GetChangedServicesRequest.first_revision:type_name -> uber.devexp.tango.BuildDescription
	2,  // 22: uber.devexp.tango.GetChangedServicesRequest.second_revision:type_name -> uber.devexp.tango.BuildDescription
	3,  // 23: uber.devexp.tango.GetChangedServicesRequest.output_config:type_name -> uber.devexp.tango.OutputConfig
	2,  // 24: uber.devexp.tango.GetChangedTargetGraphRequest.first_revision:type_name -> uber.devexp.tango.BuildDescription
	2,  // 25: uber.devexp.tango.GetChangedTargetGraphRequest.second_revision:type_name -> uber.devexp.tango.BuildDescription
	3,  // 26: uber.devexp.tango.GetChangedTargetGraphRequest.output_config:type_name -> uber.devexp.tango.OutputConfig
	6,  // 27: uber.devexp.tango.GetChangedTargetGraphResponse.changed_targets:type_name -> uber.devexp.tango.ChangedTargets
	8,  // 28: uber.devexp.tango.GetChangedTargetGraphResponse.metadata:type_name -> uber.devexp.tango.Metadata
	9,  // 29: uber.devexp.tango.Tango.GetTargetGraph:input_type -> uber.devexp.tango.GetTargetGraphRequest
	11, // 30: uber.devexp.tango.Tango.GetChangedTargets:input_type -> uber.devexp.tango.GetChangedTargetsRequest
	13, // 31: uber.devexp.tango.Tango.GetChangedServices:input_type -> uber.devexp.tango.GetChangedServicesRequest
	15, // 32: uber.devexp.tango.Tango.GetChangedTargetGraph:input_type -> uber.devexp.tango.GetChangedTargetGraphRequest
	10, // 33: uber.devexp.tango.Tango.GetTargetGraph:output_type -> uber.devexp.tango.GetTargetGraphResponse
	12, // 34: uber.devexp.tango.Tango.GetChangedTargets:output_type -> uber.devexp.tango.GetChangedTargetsResponse
	14, // 35: uber.devexp.tango.Tango.GetChangedServices:output_type -> uber.devexp.tango.GetChangedServicesResponse
	16, // 36: uber.devexp.tango.Tango.GetChangedTargetGraph:output_type -> uber.devexp.tango.GetChangedTargetGraphResponse
	33, // [33:37] is the sub-list for method output_type
	29, // [29:33] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_tango_proto_init() }
func file_tango_proto_init() {
	if File_tango_proto != nil {
		return
	}
	file_tango_proto_msgTypes[8].OneofWrappers = []any{
		(*GetTargetGraphResponse_Targets)(nil),
		(*GetTargetGraphResponse_Metadata)(nil),
	}
	file_tango_proto_msgTypes[10].OneofWrappers = []any{
		(*GetChangedTargetsResponse_ChangedTargets)(nil),
		(*GetChangedTargetsResponse_Metadata)(nil),
	}
	file_tango_proto_msgTypes[14].OneofWrappers = []any{
		(*GetChangedTargetGraphResponse_ChangedTargets)(nil),
		(*GetChangedTargetGraphResponse_Metadata)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tango_proto_rawDesc), len(file_tango_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tango_proto_goTypes,
		DependencyIndexes: file_tango_proto_depIdxs,
		EnumInfos:         file_tango_proto_enumTypes,
		MessageInfos:      file_tango_proto_msgTypes,
	}.Build()
	File_tango_proto = out.File
	file_tango_proto_goTypes = nil
	file_tango_proto_depIdxs = nil
}
