load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "mapper",
    srcs = [
        "build_description.go",
        "request_options.go",
    ],
    importpath = "github.com/uber/tango/internal/mapper",
    visibility = ["//visibility:public"],
    deps = [
        "//entity",
        "//tangopb",
    ],
)
