// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/orchestrator (interfaces: Orchestrator)
//
// Generated by this command:
//
//	mockgen -destination=orchestrator/orchestratormock/orchestratormock.go github.com/uber/tango/orchestrator Orchestrator
//

// Package mock_orchestrator is a generated GoMock package.
package mock_orchestrator

import (
	context "context"
	reflect "reflect"

	storage "github.com/uber/tango/core/storage"
	entity "github.com/uber/tango/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOrchestrator is a mock of Orchestrator interface.
type MockOrchestrator struct {
	ctrl     *gomock.Controller
	recorder *MockOrchestratorMockRecorder
	isgomock struct{}
}

// MockOrchestratorMockRecorder is the mock recorder for MockOrchestrator.
type MockOrchestratorMockRecorder struct {
	mock *MockOrchestrator
}

// NewMockOrchestrator creates a new mock instance.
func NewMockOrchestrator(ctrl *gomock.Controller) *MockOrchestrator {
	mock := &MockOrchestrator{ctrl: ctrl}
	mock.recorder = &MockOrchestratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrchestrator) EXPECT() *MockOrchestratorMockRecorder {
	return m.recorder
}

// GetTargetGraph mocks base method.
func (m *MockOrchestrator) GetTargetGraph(ctx context.Context, req entity.GetTargetGraphRequest) (storage.GraphReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetGraph", ctx, req)
	ret0, _ := ret[0].(storage.GraphReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetGraph indicates an expected call of GetTargetGraph.
func (mr *MockOrchestratorMockRecorder) GetTargetGraph(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetGraph", reflect.TypeOf((*MockOrchestrator)(nil).GetTargetGraph), ctx, req)
}
