// Code generated by MockGen. DO NOT EDIT.
// Source: core/bazel/command.go
//
// Generated by this command:
//
//	mockgen -package=commandermock -destination=core/bazel/commandermock/commandermock.go -source=core/bazel/command.go commander
//

// Package commandermock is a generated GoMock package.
package commandermock

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockcommander is a mock of commander interface.
type Mockcommander struct {
	ctrl     *gomock.Controller
	recorder *MockcommanderMockRecorder
	isgomock struct{}
}

// MockcommanderMockRecorder is the mock recorder for Mockcommander.
type MockcommanderMockRecorder struct {
	mock *Mockcommander
}

// NewMockcommander creates a new mock instance.
func NewMockcommander(ctrl *gomock.Controller) *Mockcommander {
	mock := &Mockcommander{ctrl: ctrl}
	mock.recorder = &MockcommanderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcommander) EXPECT() *MockcommanderMockRecorder {
	return m.recorder
}

// Run mocks base method.
func (m *Mockcommander) Run(stdout, stderr io.Writer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", stdout, stderr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockcommanderMockRecorder) Run(stdout, stderr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*Mockcommander)(nil).Run), stdout, stderr)
}
