// Code generated by MockGen. DO NOT EDIT.
// Source: core/bazel/command.go
//
// Generated by this command:
//
//	mockgen -package=commandermock -destination=core/bazel/commandermock/commandermock.go -source=core/bazel/command.go commander
//

// Package commandermock is a generated GoMock package.
package commandermock

import (
	io "io"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockcommander is a mock of commander interface.
type Mockcommander struct {
	ctrl     *gomock.Controller
	recorder *MockcommanderMockRecorder
	isgomock struct{}
}

// MockcommanderMockRecorder is the mock recorder for Mockcommander.
type MockcommanderMockRecorder struct {
	mock *Mockcommander
}

// NewMockcommander creates a new mock instance.
func NewMockcommander(ctrl *gomock.Controller) *Mockcommander {
	mock := &Mockcommander{ctrl: ctrl}
	mock.recorder = &MockcommanderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockcommander) EXPECT() *MockcommanderMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *Mockcommander) Start() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start")
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockcommanderMockRecorder) Start() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*Mockcommander)(nil).Start))
}

// StderrPipe mocks base method.
func (m *Mockcommander) StderrPipe() (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StderrPipe")
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StderrPipe indicates an expected call of StderrPipe.
func (mr *MockcommanderMockRecorder) StderrPipe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StderrPipe", reflect.TypeOf((*Mockcommander)(nil).StderrPipe))
}

// StdoutPipe mocks base method.
func (m *Mockcommander) StdoutPipe() (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StdoutPipe")
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StdoutPipe indicates an expected call of StdoutPipe.
func (mr *MockcommanderMockRecorder) StdoutPipe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StdoutPipe", reflect.TypeOf((*Mockcommander)(nil).StdoutPipe))
}

// Wait mocks base method.
func (m *Mockcommander) Wait() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Wait")
	ret0, _ := ret[0].(error)
	return ret0
}

// Wait indicates an expected call of Wait.
func (mr *MockcommanderMockRecorder) Wait() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wait", reflect.TypeOf((*Mockcommander)(nil).Wait))
}
