load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "storage",
    srcs = [
        "changedtargetsreader.go",
        "ctxreader.go",
        "graphreader.go",
        "graphwriter.go",
        "memstorage.go",
        "reader.go",
        "storage.go",
        "tgbgraph.go",
    ],
    importpath = "github.com/uber/tango/core/storage",
    visibility = ["//visibility:public"],
    deps = [
        "//entity",
        "//internal/streaming",
        "//internal/tgb",
        "//internal/tgbdiff",
    ],
)

go_test(
    name = "storage_test",
    srcs = [
        "storage_test.go",
        "tgbgraph_test.go",
    ],
    embed = [":storage"],
    deps = [
        "//entity",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
