package bazel

import (
	"bytes"
	"compress/gzip"
	"context"
	"fmt"
	"io"
	"os"
	"strings"

	buildpb "github.com/bazelbuild/buildtools/build_proto"
	"go.uber.org/zap"
	"google.golang.org/protobuf/proto"
)



func (b *BazelClient) setupCommand(ctx context.Context, query string, startupOptions []string, additionalArgs ...string) commander {
	// Build command: bazel <startupOpts> query <Query> --order_output=no --output=streamed_proto <AdditionalArgs>
	args := make([]string, 0, len(startupOptions)+1+len(additionalArgs)+3)
	args = append(args, startupOptions...)
	args = append(args, "query")
	args = append(args, query)
	args = append(args, "--order_output=no")
	args = append(args, "--output=streamed_proto")
	args = append(args, additionalArgs...)
	b.logger.Info("Querying Bazel", zap.String("workspacePath", b.workspacePath), zap.String("query", query))
	return b.execCommandContext(ctx, b.bazelCommand, args...)
}

func (b *BazelClient) ExecuteQuery(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	result, err := b.executeQueryInternal(ctx, req.Query, req.StartupOptions, req.AdditionalArgs...)
	if err != nil {
		return nil, err
	}
	return &QueryResponse{Result: result}, nil
}


func (b *BazelClient) executeQueryInternal(ctx context.Context, query string, startupOptions []string, additionalArgs ...string) (*buildpb.QueryResult, error) {
	var (
		stderrBuf    bytes.Buffer
		queryResults *buildpb.QueryResult
	)
	cmdCtx, cancel := context.WithTimeout(ctx, b.queryTimeout)
	defer cancel()
	// setup bazel query command
	cmd := b.setupCommand(cmdCtx, query, startupOptions, additionalArgs...)
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return nil, err
	}

	// Start the process
	if err = cmd.Start(); err != nil {
		return nil, err
	}

	queryResults, err = streamAndParseTargets(stdout)

	err = streamOutput(stderr, &stderrBuf)
	if err != nil {
		return nil, err
	}

	// Wait for both to complete to prevent zombie processes and goroutine leaks
	waitErr := cmd.Wait()

	// Get stderr for error messages
	stderrStr := stderrBuf.String()
	// Handle errors with full context (both have completed at this point)
	if waitErr != nil {
		b.logger.Error("Bazel query process failed", zap.Error(waitErr), zap.String("stderr", stderrStr))
		return nil, fmt.Errorf("bazel query process failed: %w\nstderr:\n%s", waitErr, stderrStr)
	}

	// Both succeeded
	b.logger.Debugf("Parsed %d targets from bazel query", len(queryResults.Target))
	return queryResults, nil
}


// FromFile reads a proto file generated by bazel query.
func FromFile(path string) (*buildpb.QueryResult, error) {
	var f io.ReadCloser
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	if strings.HasSuffix(path, ".gz") {
		f, err = gzip.NewReader(f)
		if err != nil {
			return nil, err
		}
	}

	out, err := io.ReadAll(f)
	if err != nil {
		return nil, err
	}

	var qr buildpb.QueryResult
	err = proto.Unmarshal(out, &qr)
	if err != nil {
		return nil, err
	}
	return &qr, nil
}
