package bazel

import (
	"compress/gzip"
	"context"
	"io"
	"os"
	"strings"

	buildpb "github.com/bazelbuild/buildtools/build_proto"
	"go.uber.org/zap"
	"google.golang.org/protobuf/proto"
)

func (b *BazelClient) setupCommand(ctx context.Context, query string, startupOptions []string, additionalArgs ...string) commander {
	// Build command: bazel <startupOpts> query <AdditionalArgs> --output=proto <Query>
	args := make([]string, 0, len(startupOptions)+1+len(additionalArgs)+2)
	args = append(args, startupOptions...)
	args = append(args, "query")
	args = append(args, additionalArgs...)
	args = append(args, "--output=proto")
	args = append(args, query)
	b.logger.Info("Querying Bazel", zap.String("workspacePath", b.workspacePath), zap.String("query", query))
	return b.execCommandContext(ctx, b.bazelCommand, args...)
}

func (b *BazelClient) ExecuteQuery(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	result, err := b.executeQueryInternal(ctx, req.Query, req.StartupOptions, req.AdditionalArgs...)
	if err != nil {
		return nil, err
	}
	return &QueryResponse{Result: result}, nil
}

func (b *BazelClient) executeQueryInternal(ctx context.Context, query string, startupOptions []string, additionalArgs ...string) (*buildpb.QueryResult, error) {
	cmdCtx, cancel := context.WithTimeout(ctx, b.queryTimeout)
	defer cancel()

	// setup bazel query command
	cmd := b.setupCommand(cmdCtx, query, startupOptions, additionalArgs...)

	// Get stdout pipe
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}

	// Start the process
	if err := cmd.Start(); err != nil {
		return nil, err
	}

	// Read all output at once (batch mode) - much faster than incremental parsing
	out, err := io.ReadAll(stdout)
	if err != nil {
		return nil, err
	}

	// Wait for command to complete
	if err := cmd.Wait(); err != nil {
		b.logger.Error("Bazel query failed: %v", err)
		return nil, err
	}

	// Single unmarshal operation - much faster than per-target streaming
	var qr buildpb.QueryResult
	if err := proto.Unmarshal(out, &qr); err != nil {
		b.logger.Error("Failed to unmarshal query result: %v", err)
		return nil, err
	}

	b.logger.Debugf("Parsed %d targets from bazel query", len(qr.Target))
	return &qr, nil
}

// FromFile reads a proto file generated by bazel query.
func FromFile(path string) (*buildpb.QueryResult, error) {
	var f io.ReadCloser
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	if strings.HasSuffix(path, ".gz") {
		f, err = gzip.NewReader(f)
		if err != nil {
			return nil, err
		}
	}

	out, err := io.ReadAll(f)
	if err != nil {
		return nil, err
	}

	var qr buildpb.QueryResult
	err = proto.Unmarshal(out, &qr)
	if err != nil {
		return nil, err
	}
	return &qr, nil
}
