// Copyright (c) 2025 Uber Technologies, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package bazel

import (
	"bytes"
	"compress/gzip"
	"context"
	"fmt"
	"io"
	"os"
	"strings"

	buildpb "github.com/bazelbuild/buildtools/build_proto"
	"go.uber.org/zap"
	"golang.org/x/sync/errgroup"
	"google.golang.org/protobuf/proto"
)

func (b *BazelClient) setupCommand(ctx context.Context, query string, startupOptions []string, additionalArgs ...string) commander {
	// Build command: bazel <startupOpts> query <AdditionalArgs> --output=streamed_proto <Query>
	args := make([]string, 0, len(startupOptions)+1+len(additionalArgs)+2)
	args = append(args, startupOptions...)
	args = append(args, "query")
	args = append(args, additionalArgs...)
	args = append(args, "--output=streamed_proto")
	args = append(args, query)
	b.logger.Debugw("Querying Bazel", zap.String("workspacePath", b.workspacePath), zap.String("query", query))
	return b.execCommandContext(ctx, b.bazelCommand, args...)
}

func (b *BazelClient) ExecuteQuery(ctx context.Context, req *QueryRequest) (*QueryResponse, error) {
	result, err := b.executeQueryInternal(ctx, req.Query, req.StartupOptions, req.AdditionalArgs...)
	if err != nil {
		return nil, err
	}
	return &QueryResponse{Result: result}, nil
}

func (b *BazelClient) executeQueryInternal(ctx context.Context, query string, startupOptions []string, additionalArgs ...string) (*buildpb.QueryResult, error) {
	var (
		stdoutBuf, stderrBuf bytes.Buffer
		queryResults         *buildpb.QueryResult
	)
	cmdCtx, cancel := context.WithTimeout(ctx, b.queryTimeout)
	defer cancel()
	// setup bazel query command
	cmd := b.setupCommand(cmdCtx, query, startupOptions, additionalArgs...)
	// Get pipes for stdout and stderr BEFORE starting the process
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return nil, err
	}
	stderr, err := cmd.StderrPipe()
	if err != nil {
		return nil, err
	}
	// In streamLogs mode, stderr goes straight to os.Stderr so operators see
	// bazel progress live; otherwise it's captured for inclusion in failure
	// errors (see wrapQueryFailure).
	stderrSink := io.Writer(&stderrBuf)
	if b.streamLogs {
		stderrSink = os.Stderr
	}
	// orchestrate `allOfFailFast`
	// create a `g` group and a new `gCtx` derived from our 15 minute timeout `ctx`.
	g, gCtx := errgroup.WithContext(cmdCtx)

	// Start the process
	if err = cmd.Start(); err != nil {
		return nil, err
	}
	// stream and parse targets
	g.Go(func() error {
		var err error
		queryResults, err = streamAndParseTargets(gCtx, stdout, &stdoutBuf)
		return err
	})
	// stream stderr
	g.Go(func() error {
		return streamOutput(gCtx, stderr, stderrSink)
	})
	waitErr := cmd.Wait()
	streamErr := g.Wait()
	if waitErr != nil {
		return queryResults, b.wrapQueryFailure("bazel query failed", waitErr, &stderrBuf)
	}
	if streamErr != nil {
		return nil, b.wrapQueryFailure("stream processing failed", streamErr, &stderrBuf)
	}
	b.logger.Debugw("Parsed targets from bazel query", zap.Int("target_count", len(queryResults.Target)))
	return queryResults, nil
}

// wrapQueryFailure logs the failure and returns a wrapped error. When stderr
// was captured (streamLogs off), its contents are appended so the failure is
// self-contained. When streamLogs is on the operator has already seen stderr
// live, so it's omitted.
func (b *BazelClient) wrapQueryFailure(msg string, cause error, stderrBuf *bytes.Buffer) error {
	tail := ""
	if !b.streamLogs {
		tail = "\nstderr:\n" + stderrBuf.String()
	}
	return fmt.Errorf("%s: %w%s", msg, cause, tail)
}

// FromFile reads a proto file generated by bazel query.
func FromFile(path string) (*buildpb.QueryResult, error) {
	var f io.ReadCloser
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	if strings.HasSuffix(path, ".gz") {
		f, err = gzip.NewReader(f)
		if err != nil {
			return nil, err
		}
	}

	out, err := io.ReadAll(f)
	if err != nil {
		return nil, err
	}

	var qr buildpb.QueryResult
	err = proto.Unmarshal(out, &qr)
	if err != nil {
		return nil, err
	}
	return &qr, nil
}
