load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "config",
    srcs = [
        "chunk_sizes.go",
        "config.go",
        "repository_config.go",
        "service_config.go",
        "storage_config.go",
    ],
    importpath = "github.com/uber/tango/config",
    visibility = ["//visibility:public"],
    deps = ["@com_github_goccy_go_yaml//:go-yaml"],
)

go_test(
    name = "config_test",
    srcs = [
        "chunk_sizes_test.go",
        "config_test.go",
    ],
    embed = [":config"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
    ],
)
