// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/core/storage (interfaces: GraphReader)
//
// Generated by this command:
//
//	mockgen -destination=storagemock/readermock.go . GraphReader
//

// Package storagemock is a generated GoMock package.
package storagemock

import (
	reflect "reflect"

	entity "github.com/uber/tango/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockGraphReader is a mock of GraphReader interface.
type MockGraphReader struct {
	ctrl     *gomock.Controller
	recorder *MockGraphReaderMockRecorder
	isgomock struct{}
}

// MockGraphReaderMockRecorder is the mock recorder for MockGraphReader.
type MockGraphReaderMockRecorder struct {
	mock *MockGraphReader
}

// NewMockGraphReader creates a new mock instance.
func NewMockGraphReader(ctrl *gomock.Controller) *MockGraphReader {
	mock := &MockGraphReader{ctrl: ctrl}
	mock.recorder = &MockGraphReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphReader) EXPECT() *MockGraphReaderMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockGraphReader) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockGraphReaderMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockGraphReader)(nil).Close))
}

// Read mocks base method.
func (m *MockGraphReader) Read() (entity.GetTargetGraphResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Read")
	ret0, _ := ret[0].(entity.GetTargetGraphResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Read indicates an expected call of Read.
func (mr *MockGraphReaderMockRecorder) Read() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockGraphReader)(nil).Read))
}
