load("@rules_go//go:def.bzl", "go_binary", "go_library")

go_library(
    name = "decode-graph_lib",
    srcs = ["main.go"],
    importpath = "github.com/uber/tango/tools/decode-graph",
    visibility = ["//visibility:private"],
    deps = [
        "//tangopb",
        "@com_github_gogo_protobuf//io",
    ],
)

go_binary(
    name = "decode-graph",
    embed = [":decode-graph_lib"],
    visibility = ["//visibility:public"],
)
