// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/core/git (interfaces: Interface)
//
// Generated by this command:
//
//	mockgen -destination=core/git/gitmock/gitmock.go github.com/uber/tango/core/git Interface
//

// Package gitmock is a generated GoMock package.
package gitmock

import (
	context "context"
	reflect "reflect"

	git "github.com/uber/tango/core/git"
	gomock "go.uber.org/mock/gomock"
)

// MockInterface is a mock of Interface interface.
type MockInterface struct {
	ctrl     *gomock.Controller
	recorder *MockInterfaceMockRecorder
	isgomock struct{}
}

// MockInterfaceMockRecorder is the mock recorder for MockInterface.
type MockInterfaceMockRecorder struct {
	mock *MockInterface
}

// NewMockInterface creates a new mock instance.
func NewMockInterface(ctrl *gomock.Controller) *MockInterface {
	mock := &MockInterface{ctrl: ctrl}
	mock.recorder = &MockInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockInterface) EXPECT() *MockInterfaceMockRecorder {
	return m.recorder
}

// ApplyPatch mocks base method.
func (m *MockInterface) ApplyPatch(ctx context.Context, patch []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyPatch", ctx, patch)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyPatch indicates an expected call of ApplyPatch.
func (mr *MockInterfaceMockRecorder) ApplyPatch(ctx, patch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyPatch", reflect.TypeOf((*MockInterface)(nil).ApplyPatch), ctx, patch)
}

// Checkout mocks base method.
func (m *MockInterface) Checkout(ctx context.Context, ref string, options ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, ref}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Checkout", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkout indicates an expected call of Checkout.
func (mr *MockInterfaceMockRecorder) Checkout(ctx, ref any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, ref}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockInterface)(nil).Checkout), varargs...)
}

// Clone mocks base method.
func (m *MockInterface) Clone(ctx context.Context, target, destination string, options ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, target, destination}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Clone", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clone indicates an expected call of Clone.
func (mr *MockInterfaceMockRecorder) Clone(ctx, target, destination any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, target, destination}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clone", reflect.TypeOf((*MockInterface)(nil).Clone), varargs...)
}

// Commit mocks base method.
func (m *MockInterface) Commit(ctx context.Context, message string, options ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, message}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Commit", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockInterfaceMockRecorder) Commit(ctx, message any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, message}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockInterface)(nil).Commit), varargs...)
}

// Diff mocks base method.
func (m *MockInterface) Diff(ctx context.Context, baseRef, targetRef string, options ...string) ([]byte, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, baseRef, targetRef}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Diff", varargs...)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Diff indicates an expected call of Diff.
func (mr *MockInterfaceMockRecorder) Diff(ctx, baseRef, targetRef any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, baseRef, targetRef}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Diff", reflect.TypeOf((*MockInterface)(nil).Diff), varargs...)
}

// Fetch mocks base method.
func (m *MockInterface) Fetch(ctx context.Context, remote, ref string, options ...string) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx, remote, ref}
	for _, a := range options {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Fetch", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Fetch indicates an expected call of Fetch.
func (mr *MockInterfaceMockRecorder) Fetch(ctx, remote, ref any, options ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, remote, ref}, options...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Fetch", reflect.TypeOf((*MockInterface)(nil).Fetch), varargs...)
}

// FileHashes mocks base method.
func (m *MockInterface) FileHashes(ctx context.Context, ref string) (map[string][]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileHashes", ctx, ref)
	ret0, _ := ret[0].(map[string][]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileHashes indicates an expected call of FileHashes.
func (mr *MockInterfaceMockRecorder) FileHashes(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileHashes", reflect.TypeOf((*MockInterface)(nil).FileHashes), ctx, ref)
}

// IsAncestor mocks base method.
func (m *MockInterface) IsAncestor(ctx context.Context, ancestorRef, descendantRef string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAncestor", ctx, ancestorRef, descendantRef)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAncestor indicates an expected call of IsAncestor.
func (mr *MockInterfaceMockRecorder) IsAncestor(ctx, ancestorRef, descendantRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAncestor", reflect.TypeOf((*MockInterface)(nil).IsAncestor), ctx, ancestorRef, descendantRef)
}

// RevParse mocks base method.
func (m *MockInterface) RevParse(ctx context.Context, ref string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RevParse", ctx, ref)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RevParse indicates an expected call of RevParse.
func (mr *MockInterfaceMockRecorder) RevParse(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RevParse", reflect.TypeOf((*MockInterface)(nil).RevParse), ctx, ref)
}

// DiffWithStatus mocks base method.
func (m *MockInterface) DiffWithStatus(ctx context.Context, baseRef, targetRef string) ([]git.DiffEntry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiffWithStatus", ctx, baseRef, targetRef)
	ret0, _ := ret[0].([]git.DiffEntry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DiffWithStatus indicates an expected call of DiffWithStatus.
func (mr *MockInterfaceMockRecorder) DiffWithStatus(ctx, baseRef, targetRef any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiffWithStatus", reflect.TypeOf((*MockInterface)(nil).DiffWithStatus), ctx, baseRef, targetRef)
}

// GetCommitTimeSecond mocks base method.
func (m *MockInterface) GetCommitTimeSecond(ctx context.Context, ref string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCommitTimeSecond", ctx, ref)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCommitTimeSecond indicates an expected call of GetCommitTimeSecond.
func (mr *MockInterfaceMockRecorder) GetCommitTimeSecond(ctx, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCommitTimeSecond", reflect.TypeOf((*MockInterface)(nil).GetCommitTimeSecond), ctx, ref)
}

// SubmoduleUpdate mocks base method.
func (m *MockInterface) SubmoduleUpdate(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SubmoduleUpdate", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SubmoduleUpdate indicates an expected call of SubmoduleUpdate.
func (mr *MockInterfaceMockRecorder) SubmoduleUpdate(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SubmoduleUpdate", reflect.TypeOf((*MockInterface)(nil).SubmoduleUpdate), ctx)
}
