// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/controller (interfaces: Controller)
//
// Generated by this command:
//
//	mockgen -destination=controller/controllermock/controllermock.go github.com/uber/tango/controller Controller
//

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	context "context"
	reflect "reflect"

	config "github.com/uber/tango/config"
	storage "github.com/uber/tango/core/storage"
	entity "github.com/uber/tango/entity"
	tangopb "github.com/uber/tango/tangopb"
	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// GetChangedTargets mocks base method.
func (m *MockController) GetChangedTargets(request *tangopb.GetChangedTargetsRequest, stream tangopb.TangoServiceGetChangedTargetsYARPCServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangedTargets", request, stream)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetChangedTargets indicates an expected call of GetChangedTargets.
func (mr *MockControllerMockRecorder) GetChangedTargets(request, stream any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangedTargets", reflect.TypeOf((*MockController)(nil).GetChangedTargets), request, stream)
}

// GetTargetGraph mocks base method.
func (m *MockController) GetTargetGraph(ctx context.Context, request entity.GetTargetGraphRequest, repo config.RepositoryConfig) (storage.GraphReader, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetGraph", ctx, request, repo)
	ret0, _ := ret[0].(storage.GraphReader)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTargetGraph indicates an expected call of GetTargetGraph.
func (mr *MockControllerMockRecorder) GetTargetGraph(ctx, request, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetGraph", reflect.TypeOf((*MockController)(nil).GetTargetGraph), ctx, request, repo)
}
