// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/controller (interfaces: Controller)
//
// Generated by this command:
//
//	mockgen -destination=controller/controllermock/controllermock.go github.com/uber/tango/controller Controller
//

// Package mock_controller is a generated GoMock package.
package mock_controller

import (
	reflect "reflect"

	tangopb "github.com/uber/tango/tangopb"
	gomock "go.uber.org/mock/gomock"
)

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// GetChangedTargetGraph mocks base method.
func (m *MockController) GetChangedTargetGraph(arg0 *tangopb.GetChangedTargetGraphRequest, arg1 tangopb.TangoServiceGetChangedTargetGraphYARPCServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangedTargetGraph", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetChangedTargetGraph indicates an expected call of GetChangedTargetGraph.
func (mr *MockControllerMockRecorder) GetChangedTargetGraph(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangedTargetGraph", reflect.TypeOf((*MockController)(nil).GetChangedTargetGraph), arg0, arg1)
}

// GetChangedTargets mocks base method.
func (m *MockController) GetChangedTargets(arg0 *tangopb.GetChangedTargetsRequest, arg1 tangopb.TangoServiceGetChangedTargetsYARPCServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChangedTargets", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetChangedTargets indicates an expected call of GetChangedTargets.
func (mr *MockControllerMockRecorder) GetChangedTargets(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChangedTargets", reflect.TypeOf((*MockController)(nil).GetChangedTargets), arg0, arg1)
}

// GetTargetGraph mocks base method.
func (m *MockController) GetTargetGraph(arg0 *tangopb.GetTargetGraphRequest, arg1 tangopb.TangoServiceGetTargetGraphYARPCServer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTargetGraph", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// GetTargetGraph indicates an expected call of GetTargetGraph.
func (mr *MockControllerMockRecorder) GetTargetGraph(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTargetGraph", reflect.TypeOf((*MockController)(nil).GetTargetGraph), arg0, arg1)
}
