load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handler",
    srcs = [
        "getchangedtargetgraph.go",
        "getchangedtargets.go",
        "gettargetgraph.go",
        "handler.go",
    ],
    importpath = "github.com/uber/tango/handler",
    visibility = ["//visibility:public"],
    deps = [
        "//controller",
        "//tangopb",
    ],
)

go_test(
    name = "handler_test",
    srcs = [
        "getchangedtargetgraph_test.go",
        "getchangedtargets_test.go",
        "gettargetgraph_test.go",
    ],
    embed = [":handler"],
    deps = [
        "//controller/controllermock",
        "//tangopb",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@org_uber_go_mock//gomock",
    ],
)
