load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "handler",
    srcs = [
        "errors.go",
        "getchangedtargetgraph.go",
        "getchangedtargets.go",
        "gettargetgraph.go",
        "handler.go",
        "metrics.go",
    ],
    importpath = "github.com/uber/tango/handler",
    visibility = ["//visibility:public"],
    deps = [
        "//config",
        "//controller",
        "//core/errors",
        "//internal/mapper",
        "//mapper/proto",
        "//observability/metrics",
        "//tangopb",
        "@com_github_uber_go_tally//:tally",
        "@org_uber_go_fx//:fx",
        "@org_uber_go_yarpc//yarpcerrors",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "handler_test",
    srcs = [
        "getchangedtargetgraph_test.go",
        "getchangedtargets_test.go",
        "gettargetgraph_test.go",
        "handler_test.go",
        "metrics_test.go",
        "testhelper_test.go",
        "wireerror_test.go",
    ],
    embed = [":handler"],
    deps = [
        "//config",
        "//controller",
        "//controller/controllermock",
        "//core/errors",
        "//core/storage",
        "//core/storage/storagemock",
        "//entity",
        "//tangopb",
        "//tangopb/tangopbmock",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@com_github_uber_go_tally//:tally",
        "@org_uber_go_mock//gomock",
        "@org_uber_go_yarpc//encoding/protobuf",
        "@org_uber_go_yarpc//yarpcerrors",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zaptest",
    ],
)
