load("@rules_go//go:def.bzl", "go_library")

go_library(
    name = "workspacemock",
    srcs = ["workspacemock.go"],
    importpath = "github.com/uber/tango/internal/workspacemock",
    visibility = ["//visibility:public"],
    deps = [
        "//core/workspace",
        "@org_uber_go_mock//gomock",
    ],
)
