// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/core/workspace (interfaces: Workspace)
//
// Generated by this command:
//
//	mockgen -destination=internal/workspacemock/workspacemock.go github.com/uber/tango/core/workspace Workspace
//

// Package mock is a generated GoMock package.
package workspacemock

import (
	context "context"
	reflect "reflect"

	workspace "github.com/uber/tango/core/workspace"
	gomock "go.uber.org/mock/gomock"
)

// MockWorkspace is a mock of Workspace interface.
type MockWorkspace struct {
	ctrl     *gomock.Controller
	recorder *MockWorkspaceMockRecorder
	isgomock struct{}
}

// MockWorkspaceMockRecorder is the mock recorder for MockWorkspace.
type MockWorkspaceMockRecorder struct {
	mock *MockWorkspace
}

// NewMockWorkspace creates a new mock instance.
func NewMockWorkspace(ctrl *gomock.Controller) *MockWorkspace {
	mock := &MockWorkspace{ctrl: ctrl}
	mock.recorder = &MockWorkspaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkspace) EXPECT() *MockWorkspaceMockRecorder {
	return m.recorder
}

// ApplyRequests mocks base method.
func (m *MockWorkspace) ApplyRequests(ctx context.Context, requests []workspace.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyRequests", ctx, requests)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyRequests indicates an expected call of ApplyRequests.
func (mr *MockWorkspaceMockRecorder) ApplyRequests(ctx, requests any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyRequests", reflect.TypeOf((*MockWorkspace)(nil).ApplyRequests), ctx, requests)
}

// Checkout mocks base method.
func (m *MockWorkspace) Checkout(ctx context.Context, remote, ref string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Checkout", ctx, remote, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// Checkout indicates an expected call of Checkout.
func (mr *MockWorkspaceMockRecorder) Checkout(ctx, remote, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Checkout", reflect.TypeOf((*MockWorkspace)(nil).Checkout), ctx, remote, ref)
}

// Path mocks base method.
func (m *MockWorkspace) Path() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Path")
	ret0, _ := ret[0].(string)
	return ret0
}

// Path indicates an expected call of Path.
func (mr *MockWorkspaceMockRecorder) Path() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Path", reflect.TypeOf((*MockWorkspace)(nil).Path))
}

// Release mocks base method.
func (m *MockWorkspace) Release() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release")
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockWorkspaceMockRecorder) Release() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockWorkspace)(nil).Release))
}
