load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "controller",
    srcs = [
        "controller.go",
        "getchangedtargets.go",
        "gettargetgraph.go",
        "metrics.go",
    ],
    importpath = "github.com/uber/tango/controller",
    visibility = ["//visibility:public"],
    deps = [
        "//config",
        "//core/cachekey",
        "//core/errors",
        "//core/storage",
        "//entity",
        "//internal/mapper/idmapper",
        "//internal/streaming",
        "//internal/targetdiff",
        "//internal/tgb",
        "//internal/tgbdiff",
        "//observability/metrics",
        "//orchestrator",
        "@com_github_uber_go_tally//:tally",
        "@org_uber_go_fx//:fx",
        "@org_uber_go_zap//:zap",
    ],
)

go_test(
    name = "controller_test",
    srcs = [
        "controller_test.go",
        "getchangedtargets_test.go",
        "getchangedtargets_tgb_test.go",
        "gettargetgraph_test.go",
        "testhelper_test.go",
    ],
    embed = [":controller"],
    deps = [
        "//config",
        "//core/cachekey",
        "//core/errors",
        "//core/storage",
        "//core/storage/storagemock",
        "//entity",
        "//observability/metrics",
        "//orchestrator/orchestratormock",
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@com_github_uber_go_tally//:tally",
        "@org_uber_go_mock//gomock",
        "@org_uber_go_zap//:zap",
        "@org_uber_go_zap//zaptest",
    ],
)
