// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/uber/tango/graphrunner (interfaces: GraphRunner)
//
// Generated by this command:
//
//	mockgen -destination=graphrunner/mock/mock.go github.com/uber/tango/graphrunner GraphRunner
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	targethasher "github.com/uber/tango/core/targethasher"
	workspace "github.com/uber/tango/core/workspace"
	gomock "go.uber.org/mock/gomock"
)

// MockGraphRunner is a mock of GraphRunner interface.
type MockGraphRunner struct {
	ctrl     *gomock.Controller
	recorder *MockGraphRunnerMockRecorder
	isgomock struct{}
}

// MockGraphRunnerMockRecorder is the mock recorder for MockGraphRunner.
type MockGraphRunnerMockRecorder struct {
	mock *MockGraphRunner
}

// NewMockGraphRunner creates a new mock instance.
func NewMockGraphRunner(ctrl *gomock.Controller) *MockGraphRunner {
	mock := &MockGraphRunner{ctrl: ctrl}
	mock.recorder = &MockGraphRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGraphRunner) EXPECT() *MockGraphRunnerMockRecorder {
	return m.recorder
}

// Compute mocks base method.
func (m *MockGraphRunner) Compute(ctx context.Context, ws workspace.Workspace) (targethasher.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compute", ctx, ws)
	ret0, _ := ret[0].(targethasher.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compute indicates an expected call of Compute.
func (mr *MockGraphRunnerMockRecorder) Compute(ctx, ws any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compute", reflect.TypeOf((*MockGraphRunner)(nil).Compute), ctx, ws)
}
