load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "githubpr",
    srcs = ["githubpr.go"],
    importpath = "github.com/uber/tango/core/workspace/githubpr",
    visibility = ["//visibility:public"],
)

go_test(
    name = "githubpr_test",
    srcs = ["githubpr_test.go"],
    embed = [":githubpr"],
    deps = [
        "@com_github_stretchr_testify//assert",
        "@com_github_stretchr_testify//require",
        "@net_pgregory_rapid//:rapid",
    ],
)
